### ISSUE TITLE
Backup prevention when storage is not available does not work

### ISSUE THREAD

**Issue by grote** [seedvault-app/seedvault#102]
When using a flash drive as a storage device, we use some dirty hacks to prevent the system from attempting to back up to the drive when it is not plugged in (as the system doesn't support this use-case on its own). In some cases, it was reported that a new restore set is created each time the drive is plugged in. This indicates that our hacks don't cover all cases and the system fails to backup and thus tries to re-initialize the storage for some reason. This would explain thew new restore sets being created.

A new restore set can also mess with Auto Restore if the backup of an uninstalled app is only available in an old restore set.

Workaround: #101 remind to plug it in
Also relevant: #99 - this bug can actually be a feature in that way, where we can already have multiple sets of backups ready for restore.

**Comment by grote** [comment]
@chirayudesai is it possible that this happened after restoring from a backup with that USB flash drive? In this case, we don't disable periodic system backups which will fail if the drive is not plugged in. That would explain why the system kept re-initializing the storage.

**Comment by chirayudesai** [comment]
> @chirayudesai is it possible that this happened after restoring from a backup with that USB flash drive? In this case, we don't disable periodic system backups which will fail if the drive is not plugged in. That would explain why the system kept re-initializing the storage.

Yes! I switch devices using Seedvault and take regular backups (but not daily), and there's always a new restore set.

I just initialized a backup on a device that was factory reset and not restored from anywhere, will re-plug usb after a couple days and see what happens.

**Comment by grote** [comment]
> In this case, we don't disable periodic system backups which will fail if the drive is not plugged in.

False alarm. We actually do disable periodic system backups in that case as well.

I checked the logs from two days and the system only requested the backup constants which are correctly returned to not attempt new backup for 30 days and thus no backup is attempted by the system.

However, when I plug in the flash drive (for the first time after 2 days), I get this in the log:

```json
I/KeyValueBackupTask: Initializing transport and resetting backup state
```

This seems to get caused by the [`@pm@` state being empty](http://aosp.opersys.com/xref/android-10.0.0_r45/xref/frameworks/base/services/backup/java/com/android/server/backup/keyvalue/KeyValueBackupTask.java#417) for some reason.

It would interesting to get the output of the following command, on a device where you haven't plugged in a drive for at least 24h before plugging in the drive and after the triggered backup is complete:

    ls -la /data/backup/*

It could be that [`deletePmStateFile()`](http://aosp.opersys.com/xref/android-10.0.0_r45/xref/frameworks/base/services/backup/java/com/android/server/backup/keyvalue/KeyValueBackupTask.java#622) is run for some reason. Then we should see `Transport requires initialization, rerunning` at some point in the log.

**Comment by chirayudesai** [comment]
> > In this case, we don't disable periodic system backups which will fail if the drive is not plugged in.
> 
> False alarm. We actually do disable periodic system backups in that case as well.
> 
> I checked the logs from two days and the system only requested the backup constants which are correctly returned to not attempt new backup for 30 days and thus no backup is attempted by the system.
> 
> However, when I plug in the flash drive (for the first time after 2 days), I get this in the log:
> 
> ```json
> I/KeyValueBackupTask: Initializing transport and resetting backup state
> ```
Same here. Below that, I also see:
```
09-04 22:22:12.333  1243 18480 E KeyValueBackupTask: Error during PM metadata backup                                                                                                                                                                           
09-04 22:22:12.333  1243 18480 E KeyValueBackupTask: com.android.server.backup.keyvalue.AgentException                                                                                                                                                         
09-04 22:22:12.333  1243 18480 E KeyValueBackupTask:    at com.android.server.backup.keyvalue.KeyValueBackupTask.handleTransportStatus(KeyValueBackupTask.java:892)                                                                                            
09-04 22:22:12.333  1243 18480 E KeyValueBackupTask:    at com.android.server.backup.keyvalue.KeyValueBackupTask.sendDataToTransport(KeyValueBackupTask.java:837)                                                                                              
09-04 22:22:12.333  1243 18480 E KeyValueBackupTask:    at com.android.server.backup.keyvalue.KeyValueBackupTask.sendDataToTransport(KeyValueBackupTask.java:374)                                                                                              
09-04 22:22:12.333  1243 18480 E KeyValueBackupTask:    at com.android.server.backup.keyvalue.KeyValueBackupTask.backupPm(KeyValueBackupTask.java:457)                                                                                                         
09-04 22:22:12.333  1243 18480 E KeyValueBackupTask:    at com.android.server.backup.keyvalue.KeyValueBackupTask.run(KeyValueBackupTask.java:349)                                                                                                              
09-04 22:22:12.333  1243 18480 E KeyValueBackupTask:    at java.lang.Thread.run(Thread.java:919)  
```

This last bit was when I didn't have the usb drive plugged in.
I plugged it in afterwards, and that didn't have this.
It started backing up, and created another set. (So I now have two folders in `.SeedVaultAndroidBackup` - with this device's backup.

> 
> This seems to get caused by the [`@pm@` state being empty](http://aosp.opersys.com/xref/android-10.0.0_r45/xref/frameworks/base/services/backup/java/com/android/server/backup/keyvalue/KeyValueBackupTask.java#417) for some reason.
> 
> It would interesting to get the output of the following command, on a device where you haven't plugged in a drive for at least 24h before plugging in the drive and after the triggered backup is complete:
> 
> ```
> ls -la /data/backup/*
> ```
Unfortunately this was on a `-user` build, but I can check again later.
> 
> It could be that [`deletePmStateFile()`](http://aosp.opersys.com/xref/android-10.0.0_r45/xref/frameworks/base/services/backup/java/com/android/server/backup/keyvalue/KeyValueBackupTask.java#622) is run for some reason. Then we should see `Transport requires initialization, rerunning` at some point in the log.

**Comment by grote** [comment]
> This last bit was when I didn't have the usb drive plugged in.

Thanks, that is a clue!

The code for that [is here](http://aosp.opersys.com/xref/android-10.0.0_r45/xref/frameworks/base/services/backup/java/com/android/server/backup/keyvalue/KeyValueBackupTask.java#890) which [gets triggered here](http://aosp.opersys.com/xref/android-10.0.0_r45/xref/frameworks/base/services/backup/java/com/android/server/backup/keyvalue/KeyValueBackupTask.java#349). We really do use `TRANSPORT_PACKAGE_REJECTED` to keep the system from trying to back up stuff when the drive is not available. The `AgentException.permanent()` should get caught and not cause a TaskException with compromised state, right?

**Comment by chirayudesai** [comment]
> > This last bit was when I didn't have the usb drive plugged in.
> 
> Thanks, that is a clue!
> 
> The code for that [is here](http://aosp.opersys.com/xref/android-10.0.0_r45/xref/frameworks/base/services/backup/java/com/android/server/backup/keyvalue/KeyValueBackupTask.java#890) which [gets triggered here](http://aosp.opersys.com/xref/android-10.0.0_r45/xref/frameworks/base/services/backup/java/com/android/server/backup/keyvalue/KeyValueBackupTask.java#349). We really do use `TRANSPORT_PACKAGE_REJECTED` to keep the system from trying to back up stuff when the drive is not available. The `AgentException.permanent()` should get caught and not cause a TaskException with compromised state, right?

Perhaps we want to use an alternative mechanism if available to stop the system from trying to backup, given that that's more for rejecting a specific app's backup rather than the full thing.

TODO: Revisit in 11 #94

**Comment by grote** [comment]
If somebody finds an alternative mechanism, by all means, let's use it. What we do now is the only hack I've found so far.

**Comment by grote** [comment]
More code investigation, also with the aim to find out while Nextcloud backups are triggered when phone is in airplane mode:

* Scheduling of K/V Backup [`KeyValueBackupJob`](http://aosp.opersys.com/xref/android-11.0.0_r5/xref/frameworks/base/services/backup/java/com/android/server/backup/KeyValueBackupJob.java#71)
* Scheduling of Full backup [`FullBackupJob`](http://aosp.opersys.com/xref/android-11.0.0_r5/xref/frameworks/base/services/backup/java/com/android/server/backup/FullBackupJob.java#47)

Important finding for the K/V backup is the use of [`JobInfo.Builder#setOverrideDeadline()`](https://developer.android.com/reference/android/app/job/JobInfo.Builder#setOverrideDeadline(long)):

> The job will be run by this deadline even if other requirements are not met.

So when this deadline ([one day](http://aosp.opersys.com/xref/android-11.0.0_r5/xref/frameworks/base/services/backup/java/com/android/server/backup/KeyValueBackupJob.java#55)) expires, `BackupManagerService.backupNowForUser(userId)` will get called regardless of any requirements.

This checks [`isUserReadyForBackup(userId)`](http://aosp.opersys.com/xref/android-11.0.0_r5/xref/frameworks/base/services/backup/java/com/android/server/backup/BackupManagerService.java#763) which could provide an opportunity to prevent automatic backup runs if we somehow manage to prevent the backup manager service from getting registered for the user. The most reasonable and supported way to do this seems to be to call [`BackupManager#setBackupServiceActive()`](http://aosp.opersys.com/xref/android-11.0.0_r5/xref/frameworks/base/core/java/android/app/backup/IBackupManager.aidl#589). This could be the "alternative mechanism" we were looking for above. I just need to test what side-effects it has, when this is enabled (resp. disabled). The docs mention this which is encouraging:

>  clients can still safely call BackupManager methods

While this will would help with backups to USB (the topic of this ticket), it wouldn't help with SAF providers that require a network connection as we wouldn't want to constantly monitor the availability of the (internet?) connection and turn backup on/off all the time. There, we might need to employ the 'reject' technique we already use for USB in combination with `BackupTransport#requestBackupTime()`.

**Comment by grote** [comment]
> The code for that is here which gets triggered here. We really do use TRANSPORT_PACKAGE_REJECTED to keep the system from trying to back up stuff when the drive is not available. The AgentException.permanent() should get caught and not cause a TaskException with compromised state, right?

Normally not, but the problem is that the `backupPm()` method is special in the sense that any exception thrown in it, [gets rethrown](http://aosp.opersys.com/xref/android-11.0.0_r5/xref/frameworks/base/services/backup/java/com/android/server/backup/keyvalue/KeyValueBackupTask.java#661) as `TaskException.stateCompromised(e)`. So we need to find another way to cleanly reject backups without compromising our backup state causing re-initialization.

Since I couldn't find another solution, I checked the behavior of Google backup (on an Android 7 phone) and they always return `TRANSPORT_OK`, even when Wi-Fi is off and they can't upload the `@pm@` data. Now I wonder, if they cache that data locally and upload it at the next opportunity or if they request non-incremental backup for `@pm@` next time? The logs are pretty minimal, so I can't tell.

**Comment by chirayudesai** [comment]
Quoting parts of the two comments above

> While this will would help with backups to USB (the topic of this ticket), it wouldn't help with SAF providers that require a network connection as we wouldn't want to constantly monitor the availability of the (internet?) connection and turn backup on/off all the time. There, we might need to employ the 'reject' technique we already use for USB in combination with `BackupTransport#requestBackupTime()`.

Why not constantly monitor the internet though? We could consider that as the last case option, where we simply
* Set service to inactive if usb backup, and usb not plugged in.
* Set service to inactive if offline for any other providers?

And set to active again when they're plugged in. An interruption when backing up would cause issues, but one can already accidentally unplug a usb during backup so it'd be not different.

> Since I couldn't find another solution, I checked the behavior of Google backup (on an Android 7 phone) and they always return `TRANSPORT_OK`, even when Wi-Fi is off and they can't upload the `@pm@` data. Now I wonder, if they cache that data locally and upload it at the next opportunity or if they request non-incremental backup for `@pm@` next time? The logs are pretty minimal, so I can't tell.

We should check on something recent / latest too, the behaviour might have or maybe not.

If they're caching though, I don't what to say haha, I wanted to cache since day 1, while that has it's own issues that need addressing, it would've avoided many issues here. :)

If they do it even on 11, I guess if this is still needed we could cache just @pm@ perhaps, and use the workaround for the other backups? Not sure.

**Comment by grote** [comment]
> Why not constantly monitor the internet though? We could consider that as the last case option, where we simply
> 
>    * Set service to inactive if usb backup, and usb not plugged in.
> 
>    * Set service to inactive if offline for any other providers?

Do you have an example of a system app service that reliably always runs in the background without a foreground notification and without being ever killed by the system? Is a boot broadcast receiver sufficient to start it? Furthermore, more research would be needed for how to handle several user/work profiles.

> We should check on something recent / latest too, the behaviour might have or maybe not.

I don't have anything more recent available at the moment, but this is easy to test. Set up Google backup on the phone, do one initial pass, connect via USB, disable internet access and then do something like `adb shell bmgr backupnow com.android.wallpaperbackup`. If the output contains `Package @pm@ with result: Success` and only the actual package fails to backup, then they were returning `TRANSPORT_OK` for `@pm@`.

**Comment by grote** [comment]
> call [`BackupManager#setBackupServiceActive()`](http://aosp.opersys.com/xref/android-11.0.0_r5/xref/frameworks/base/core/java/android/app/backup/IBackupManager.aidl#589). This could be the "alternative mechanism" we were looking for above.

Turns out [we are not allowed to call this](http://aosp.opersys.com/xref/android-11.0.0_r5/xref/frameworks/base/services/backup/java/com/android/server/backup/BackupManagerService.java#422) without running with system or root UID. :disappointed:

**Comment by grote** [comment]
Other options to prevent automatic backups that I looked into:

### Setup Incomplete

Before each backup, the manager [checks that setup is complete](http://aosp.opersys.com/xref/android-11.0.0_r5/xref/frameworks/base/services/backup/java/com/android/server/backup/UserBackupManagerService.java#2857). Set by an observer on `Settings.Secure#USER_SETUP_COMPLETE` which has probably other side-effects if we set this to `false`.

Also:

> If the user was previously setup and now the setting has changed to `false`, we don't reset the state as having gone through setup is a non-reversible action.

### Turning backup off

`setBackupEnabled(false)` [causes a wipe each time we turn it off](http://aosp.opersys.com/xref/android-11.0.0_r5/xref/frameworks/base/services/backup/java/com/android/server/backup/UserBackupManagerService.java#3270), so that doesn't help.

### Battery Saver Mode 

This is [a good reason to defer backups](http://aosp.opersys.com/xref/android-11.0.0_r5/xref/frameworks/base/services/backup/java/com/android/server/backup/UserBackupManagerService.java#2820). But it doesn't seem like we are able to cheat this to always report `keyvaluebackup_deferred` independent of actual battery saver state as the [`OFF_POLICY` is hard-coded](http://aosp.opersys.com/xref/android-11.0.0_r5/xref/frameworks/base/services/core/java/com/android/server/power/batterysaver/BatterySaverPolicy.java#118).

    adb shell dumpsys power | grep -C 5 keyvaluebackup_deferred

### Cancelling the `KeyValueBackupJob`

These jobs get scheduled all over the place, like [when a package reports changed data](http://aosp.opersys.com/xref/android-11.0.0_r5/xref/frameworks/base/services/backup/java/com/android/server/backup/UserBackupManagerService.java#2599). So this would be like playing whack-a-mole against the system. This is something we can't win, if we want reliability.

### Prevent our transport from starting/binding/connecting

When we refuse to start, [the system can't do backups](http://aosp.opersys.com/xref/android-11.0.0_r5/xref/frameworks/base/services/backup/java/com/android/server/backup/internal/BackupHandler.java#155) and seems to handle this gracefully. Early tests are promising.

Useful commands for testing

    adb shell dumpsys jobscheduler | grep -C 20 com.android.server.backup.KeyValueBackupJob

    adb shell cmd jobscheduler run -f android 52417896

where `52417896` is the `JOB_ID` taken from

```
  JOB #1000/52417896: 8ef62e1 android/com.android.server.backup.KeyValueBackupJob
```

Problem is that even if returning `null` in `Service#onBind()`, we [`bindServiceAsUser()` is returning true](http://aosp.opersys.com/xref/android-11.0.0_r5/xref/frameworks/base/services/backup/backuplib/java/com/android/server/backup/transport/TransportClient.java#217) maybe because we connected for registration. So the state transitions from `IDLE` to `BOUND_AND_CONNECTING` and stays for some time (more than 5min at least). And when it finally finished (after `604750 ms` in my tests) it goes into `UNUSABLE` state which might have severe side-effects such as all interactions (even if flash drive got plugged in or network connection came back) are hanging, because the system can't or doesn't want to connect to the transport anymore.

### Cancelling all backups early on

When asked for available quota for `@pm@`, we could try to cancel all backups. When doing this, the log looks promising:

```
D/KeyValueBackupTask: Starting key-value backup of @pm@
D/KeyValueBackupTask: Invoking agent on @pm@
D/KeyValueBackupTask: Data file: /data/cache/backup_stage/@pm@.data
I/BackupCoordinator: Get backup quota for @pm@. Is full backup: false.
I/BackupManagerService: [UserID:0] cancelBackups() called.
V/BackupManagerService: [UserID:0] Cancel: token=ec73f9a
V/BackupManagerService: [UserID:0]    Invoking cancel on com.android.server.backup.keyvalue.KeyValueBackupTask@3401cd6
V/KeyValueBackupTask: Cancel received
```

but `adb shell bmgr backupnow` is hanging just like when not starting the transport service. Subsequent backup requests don't work anymore as this seems to trigger a bug inside `UserBackupManagerService` where it [loses track of the operation token](http://aosp.opersys.com/xref/android-11.0.0_r5/xref/frameworks/base/services/backup/java/com/android/server/backup/UserBackupManagerService.java#2009) and [tries to remove it two times](http://aosp.opersys.com/xref/android-11.0.0_r5/xref/frameworks/base/services/backup/java/com/android/server/backup/keyvalue/KeyValueBackupTask.java#766).

Cancelling in `Service#onBind()` is worse as this produces a user-visible ANR.

Last option is to cancel short before actually performing the `@pm@` backup, but this causes the same `Duplicate remove for operation` bug. Tracking this down and fixing it will probably not help as cancellation gets only handled after the K/V task [has already finished](http://aosp.opersys.com/xref/android-11.0.0_r5/xref/frameworks/base/services/backup/java/com/android/server/backup/keyvalue/KeyValueBackupTask.java#769) and some comment says that it [doesn't require cancellation](http://aosp.opersys.com/xref/android-11.0.0_r5/xref/frameworks/base/services/backup/java/com/android/server/backup/UserBackupManagerService.java#2103).

---

Conclusion: After spending a crazy amount of time researching all this, the only option left seems to be what Google Backup is doing all along and just return `TRANSPORT_OK` even though things were not OK. Then we only need to ensure somehow that they get into an OK state again during the next backup run we actually can perform.

The easiest and less complex way to do this could be to just remember that we need to insist on non-incremental `@pm@` backup next time we get asked to back that up.

**Comment by chirayudesai** [comment]
> Other options to prevent automatic backups that I looked into:
> 
> ### Setup Incomplete
This affects a bunch of other stuff and would only lead to issues. It's set by SetupWizard, remember that time you tried to emulate SetupWizard for the restore activity? This is one of the bits that may have missed, and there's one more too, but that's not relevant here.

However, if there's no other way, we could add a check here for our very own setting.

> ### Battery Saver Mode

Same here, instead of (ab)using this mode, we can just add our own check where it checks for this.

> ### All other options

Sounds like they all have one or the other downside, so best to skip those.

> 
> Conclusion: After spending a crazy amount of time researching all this, the only option left seems to be what Google Backup is doing all along and just return `TRANSPORT_OK` even though things were not OK. Then we only need to ensure somehow that they get into an OK state again during the next backup run we actually can perform.

Thanks for spending the time on this! Sticking with what Google Backup does makes a lot of sense, they'd ensure it stays working, and if it ever breaks (say Android 12), we can just revisit this here and/or see what they're doing :)

> 
> The easiest and less complex way to do this could be to just remember that we need to insist on non-incremental `@pm@` backup next time we get asked to back that up.

Sounds like a plan.

We should definitely do a quick verification on latest stock to see if it still matches this, otherwise this sounds good.

**Comment by grote** [comment]
> just return `TRANSPORT_OK` even though things were not OK [...]
> remember that we need to insist on non-incremental `@pm@` backup next time we get asked to back that up.

For the record, I've tried this and it seems to work fine. Things fail after `@pm@` is (fake) done, but state isn't compromised and next time, the system accepts to do a full (non-incremental) `@pm@` backup and otherwise continues where it left off.

---

The only thing I am not sure about is what happens when we make a fake `@pm@` backup, then the usb is plugged in or internet comes back, the backup continues without error and then the phone breaks making the user restore that backup. Will the missed `@pm@` backup cause any problems? 

Since the main thing in this backup is [each installed app's signature hash and version code](http://aosp.opersys.com/xref/android-11.0.0_r8/xref/frameworks/base/services/backup/java/com/android/server/backup/PackageManagerBackupAgent.java#311), it could happen that a new app gets backed up, but we didn't get its signature hash, so [it won't be restored](http://aosp.opersys.com/xref/android-11.0.0_r8/xref/frameworks/base/services/backup/java/com/android/server/backup/restore/PerformUnifiedRestoreTask.java#517) in the above scenario. However, since this was an automatic backup failure which can happen, then this can be considered equivalent to the system not having had a chance to backup that new app.

**Comment by grote** [comment]
This commit from Android 12 is related and seems to fix the issue: https://gitlab.com/CalyxOS/platform_frameworks_base/-/commit/819ed81faaa295d9e1096f13f599cb43d48cda88

**Comment by grote** [comment]
This should now be fixed.
