### ISSUE TITLE
Setup Wizard is not advancing after restore

### ISSUE THREAD

**Issue by mikeNG** [seedvault-app/seedvault#115]
This might not be a seedvault bug but a setup wizard bug. When you finish restoring a backup in the wizard, it takes the user back to the same page where it asks to restore a backup or skip it. Attempting to restore a second time fails. Expected behavior would be to take the user to the final page of setup wizard instead of the previous page.

**Comment by grote** [comment]
We are launching the `RestoreActivity` using [`startSubactivity`](https://gitlab.com/calyxos/platform_packages_apps_setupwizard/-/blob/727297955d6055405112ba89fd4bd944d0de76b4/src/org/calyxos/setupwizard/backup/RestoreIntroActivity.java#L40) and when the user clicks [Finish], we [set `RESULT_OK`](https://github.com/stevesoltys/seedvault/blob/a585324c710719df5157712ab6707ed9bc82e2fe/app/src/main/java/com/stevesoltys/seedvault/restore/RestoreProgressFragment.kt#L42) before finishing the activity.

**Comment by chirayudesai** [comment]
SUW code: https://gitlab.com/calyxos/platform_packages_apps_setupwizard/-/blob/android10/src/org/calyxos/setupwizard/backup/RestoreIntroActivity.java

**Comment by mikeNG** [comment]
This was an issue in SetupWizard and should be fixed for CalyxOS Android 11 builds (and LineageOS 17.1/18.0)
