### ISSUE TITLE
LineageOS integration

### ISSUE THREAD

**Issue by chirayudesai** [seedvault-app/seedvault#118]
This issue is for tracking integration of Seedvault into LineageOS 17.1

- [x] repo forked [[link](https://github.com/LineageOS/android_packages_apps_Seedvault)]
- [x] builds (smoke test)
- [x] SUW fixes #115
- [x] Settings backup provider toggle
- [x] Test nicety with GApps
- [x] shipped

**Comment by grote** [comment]
I wrote [a patch](https://gitlab.com/calyxos/platform_packages_apps_settings/-/commits/change-backup-transport/) that allows the user to change the backup transport (e.g. switch between Seedvault and Google backup).

**Comment by chirayudesai** [comment]
See https://review.lineageos.org/q/topic:%22seedvault%22 and https://review.lineageos.org/q/project:LineageOS%252Fandroid_packages_apps_Seedvault

**Comment by chirayudesai** [comment]
This has been shipping since a while! Thanks @mikeNG 

It's available in LineageOS 17.1 and 18.0
