### ISSUE TITLE
Oreo support

### ISSUE THREAD

**Issue by hockeymikey** [seedvault-app/seedvault#137]
So from my understanding is that the project needs to be migrated back over to Java to be able to be compiled with Oreo since older soong versions don't have Kotlin support and Android.mk sure doesn't. Correct me if I'm wrong, migrating over is a pain and I'd rather keep in line with the upstream being Kotlin.

**Comment by grote** [comment]
You should be able to use it with Oreo as a prebuilt APK like we had until recently (#119) without migrating anything to Java. However, you will need to revert a few API adaptions to work on Oreo again.

**Comment by hockeymikey** [comment]
> You should be able to use it with Oreo as a prebuilt APK like we had until recently (#119) without migrating anything to Java. However, you will need to revert a few API adaptions to work on Oreo again.

Good idea, that'll work. Don't suppose there is a way to include that part of the the AOSP build. I figure how I can do it, building the gradle project and the android.mk file as you reference, but just curious if there is a way to build it with the rom that you know off the top of your head. Just weighing my options.

**Comment by stevesoltys** [comment]
I don't think it would be easily achievable to build it with Oreo besides in prebuilt format.

If you get Oreo working with the latest code in `master`, feel free to let us know and we can create an `android8` branch for those who are interested (we would not be maintaining it though, it would be up to the community to submit PRs).

**Comment by grote** [comment]
I think the question has been answered.

**Comment by hockeymikey** [comment]
> I think the question has been answered.

I also implemented it for oreo again and have the complete build system setup. Someday I'll get around to making a pull request probably when encryption switching is implemented.
