### ISSUE TITLE
Don't backup APKs to network storage when on metered network

### ISSUE THREAD

**Issue by grote** [seedvault-app/seedvault#149]
APK backups for apps that opted out of data backup happen as part of K/V backups which can also be [triggered outside of the normal K/V scheduling](http://aosp.opersys.com/xref/android-11.0.0_r8/xref/frameworks/base/services/backup/java/com/android/server/backup/KeyValueBackupJob.java#101) which would normally only happen on un-metered networks while charging.

So if somebody doesn't charge their phone on un-metered networks for more than a day, the system will tell us to do a K/V backup pass anyway. We should at least skip the APK backups in that case as these can cause large traffic volume the user might need to pay for.

The work done for #102 will make this easier.

**Comment by chirayudesai** [comment]
I feel like we should have an option to not do any form of backup at all on a metered network, if that's what the user wants. It'd be basically be like if you don't have a usb drive connected, which we already have to account for.

**Comment by grote** [comment]
This should get solved by #583

**Comment by grote** [comment]
closed by #628
