### ISSUE TITLE
GitHub Actions for CI

### ISSUE THREAD

**Issue by chirayudesai** [seedvault-app/seedvault#159]
It's integrated nicely, and works well.

Our CI job is quite simple so it should be easy to switch over.

**Comment by stevesoltys** [comment]
One thing to note is we'd be limited to 2000 minutes per month (Travis is unlimited for open source).

I think that's plenty, at least with the current state of tests / number of contributions. If we did hit that limit, I'd probably just pay for GitHub teams :)

**Comment by chirayudesai** [comment]
https://news.ycombinator.com/item?id=25003387 This is what I was trying to find earlier, but couldn't.

Article: https://www.jeffgeerling.com/blog/2020/travis-cis-new-pricing-plan-threw-wrench-my-open-source-works

Also see: https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

The problematic part:

> We will be offering an allotment of OSS minutes that will be reviewed and allocated on a case by case basis. Should you want to apply for these credits please open a request with Travis CI support stating that you’d like to be considered for the OSS allotment. Please include:
> * Your account name and VCS provider How many credits (build minutes) you’d like to request (should your run out of credits again you can repeat the process to request more or discuss a renewable amount)

The article mentions 1000 minutes, so 2000 is already better.

Additionally and more importantly, we can bring our own runner here, which means unlimited minutes, if ever needed, without having to switch CI systems again.

**Comment by stevesoltys** [comment]
Closed via #160.
