### ISSUE TITLE
Enhancement requests: SFTP as a backup location, manual backups; documentation question

### ISSUE THREAD

**Issue by FBachofner** [seedvault-app/seedvault#171]
It would be great to have an **SFTP server address + port + folder as a backup location** possibility.

It would _also_ be great to be able to **invoke a backup manually** (for "instantaneous" currency when moving the backup to a new device).

A few questions:
1. Is there a forum (I'm always uncomfortable using GitHub for general Q&A)?
2. End-user documentation?

Some things seem quite unclear.  For example:

Restores: moving the folder to a new device and pointing SeedVault at the folder where I put it does not in any way yield a "restore button."

Does one have to restore apps by individually reinstalling each APK in the backup?  Even on the original device there is no restore button.  This seems like a huge waste of time.

If the concept is to install each APK individually, then how does one restore the encrypted data?  Sorry if I am being dense or otherwise overlooking something obvious.

FYI: I am playing with SeedVault on LineageOS 18 (Android 11) on a rooted Xiaomi Redmi Note 9 Pro.

**Comment by stevesoltys** [comment]
If you could, please separate each feature request into its own issue (make sure to check that they are not duplicates).

To answer your first question - we don't have a forum, but we do have an IRC channel on Freenode: `#seedvault`.

**Comment by grote** [comment]
> It would be great to have an SFTP server address + port + folder as a backup location possibility.

I agree. Please do it!

> It would also be great to be able to invoke a backup manually (for "instantaneous" currency when moving the backup to a new device).

Doesn't this already work? Did you check the overflow menu on the main screen?

> Restores: moving the folder to a new device and pointing SeedVault at the folder where I put it does not in any way yield a "restore button."

See https://github.com/seedvault-app/seedvault/issues/85

Did you not see the restore option in Lineage's SetupWizard?

> Does one have to restore apps by individually reinstalling each APK in the backup? Even on the original device there is no restore button.

No, Seedvault restores the APKs for you.

> If the concept is to install each APK individually, then how does one restore the encrypted data?

Seedvault does it for you, once you actually do a restore.

**Comment by FBachofner** [comment]
Thank you @grote for your comments

> > It would also be great to be able to invoke a backup manually (for "instantaneous" currency when moving the backup to a new device).
> 
> Doesn't this already work? Did you check the overflow menu on the main screen?

Found it shortly after commenting here.  Seems to work, but feedback is somewhat poor.  No progress bar, for example, so it is basically impossible to tell what is going on.

Backups do seem to occur correctly, however.

 
> > Restores: moving the folder to a new device and pointing SeedVault at the folder where I put it does not in any way yield a "restore button."
> 
> See #85
> 
> Did you not see the restore option in Lineage's SetupWizard?

I did, but kept getting error messages.

Then it occurred to me the problem might be that my file transferred from another device was not in the root of the OTG memory stick.  That was it!

I think SeedVault should have a file/folder browser even on initial setup.  I will add an enhancement request.

Thanks again!

**Comment by grote** [comment]
> Seems to work, but feedback is somewhat poor. No progress bar, for example, so it is basically impossible to tell what is going on.

I guess you didn't notice the notification in the status bar or was there none?

**Comment by FBachofner** [comment]
> > Seems to work, but feedback is somewhat poor. No progress bar, for example, so it is basically impossible to tell what is going on.
> 
> I guess you didn't notice the notification in the status bar or was there none?

I'm pretty sure there was a notification when the backup was complete.  **But there was zero feedback that something happened at the moment I invoked the backup manually, nor shortly afterwards.**

Given how long a backup of a complex device can take, it would seem prudent to show some kind of pregress indicator, no?

Perhaps Android does not contemplate this (vs. a conventional operating system)?

**Comment by FBachofner** [comment]
I just reconfigured everything on a test phone and I am indeed seeing a backup progress bar, but only in the notification shade.

That's obviously fine if that is what the SeedVault developers intend.

Hopefully some documentation will become available (beyond the meager wiki here.

FYI, I would be happy to help edit such documentation as I can not provide coding/development assistance.

**Comment by grote** [comment]
> Hopefully some documentation will become available (beyond the meager wiki here).

> FYI, I would be happy to help edit such documentation as I can not provide coding/development assistance.

Help with the documentation would be appreciated. You could document what you have learned so far. Do you have permission to edit the wiki?
