### ISSUE TITLE
Backup to SFTP

### ISSUE THREAD

**Issue by FBachofner** [seedvault-app/seedvault#173]
It would be great to have an SFTP server address + port + folder as a backup location option.

Why:
1. Not everyone wants the "weight" of NextCloud.on their server(s)
2. Local backup requires an extra step to sync / transfer.
3. USB-OTG is not always physically available and/or flaky on some devices

Thank you for your consideration.

[ I am posting this enhancement request as a separate issue as per @stevesoltys comment in #171 (now closed by me) ]
.

**Comment by chirayudesai** [comment]
One good way to have this is adding support for an existing SFTP app that supports SAF.

That means that there's only a one line change needed to Seedvault, adding that app to the whitelist of supported providers, if it works well. It'd be similar to #167 and #169

**Comment by renatobellotti** [comment]
Has somebody found the time to look into this? I'd love to have this feature.

**Comment by Flunkyball** [comment]
I would be interested in that two.
Meanwhile I configured my SFTP share in Nextcloud as external storage and have seedvault backup it to that location. Kind of a workaround but performance would be much better if access via SFTP would be directly available.

**Comment by basemod** [comment]
Would be pretty cool, because in that case I could backup to my home NAS. 👍

**Comment by Silent-Hunter** [comment]
I too would love this! Then I wouldn't have to plug a thumbdrive into my phone to back it up.

**Comment by simonsan** [comment]
This would be awesome. I started using a [storage box](https://www.hetzner.com/storage/storage-box) and I would love to keep my encrypted backups there. For that it would be nice to also deposit my public key within Seedvault, see https://github.com/seedvault-app/seedvault/issues/138

**Comment by Stebalien** [comment]
[ftpclient](https://codeberg.org/qwerty287/ftpclient/issues/33) now supports the storage access framework. It works with FTP, FTPS, and SFTP.

**Comment by grote** [comment]
This can now be used via Roundsync added in #609

**Comment by simonsan** [comment]
@grote By the way, not sure if it's worth it to open another issue for it, but opendal is probably also worth to be looked into: https://central.sonatype.com/artifact/org.apache.opendal/opendal-java

https://opendal.apache.org/

**Comment by HubKing** [comment]
> This can now be used via Roundsync added in #609

I installed RS, but it did not show up in SeedVault's target location list. SeedVault is the version that came with LineageOS 21 latest night, version 14-4.0. Is it not showing because #609 is not released yet or  you mean that I choose the phone's local storage for SeedVault's target location, and then use RS to synchronise the ".SeedVaultAndroidBackup" directory with an SFTP server?

**Comment by grote** [comment]
No, as far as I understand (@stevesoltys may know more) you install the Roundsync app, set up SFTP there and then it will show up as an option in Seedvault.

**Comment by stevesoltys** [comment]
You need to set "Enable Content Provider Preview" on in RSync configuration under "File Access".
