### ISSUE TITLE
Reset "12-word recovery code" via UI

### ISSUE THREAD

**Issue by FBachofner** [seedvault-app/seedvault#174]
SeedVault would be incredibly useful to "clone" a configuration from one phone to another.

But what if the 2nd, 3rd, nth phone belongs to a different user?

Restoring from a SeedVault backup permanently(?)injects the "12-word recovery code" onto the nth device too.

There does not seem to be a way to reset the "12-word recovery code" so now that code would need to be shared with the owner of the 9th device.  It seems this might make the owner of the source (i.e. 1st) device slightly more vulnerable.

I guess/bet there is already a way to reset the "12-word recovery code," but it does not seem exposed in the UI . . .

Adding this would also be beneficial to such users who have not written down their recovery code and want to reconfigure their backup system.

Thank you for your consideration.

**Comment by chirayudesai** [comment]
Duplicate of #62 

Has been implemented already, see https://github.com/seedvault-app/seedvault/pull/168

**Comment by chirayudesai** [comment]
In the interim, you can simply clear Seedvault app data from Settings -> Apps to reset the code.

**Comment by FBachofner** [comment]
> In the interim, you can simply clear Seedvault app data from Settings -> Apps to reset the code.

**Thank you for the tip!!**

Sorry I posted a duplicate.  Bad me -- scrolled through the list (and not far enough!) instead of using search.
