### ISSUE TITLE
Backport fix for backup wipe issue to Android 10

### ISSUE THREAD

**Issue by EmanuelLoos** [seedvault-app/seedvault#175]
My Setup:
I have got Seedvault version 1.0.0 on a Fairphone 3+ using an(Android 10) unofficial LinageOS with microG build (treble_arm64_bvN-userdebug 10 QQ3A.200805.001 eng.buildb.20201113.161515) setup with Nextcloud running a bit unstable but working on my own server.

Seedvault's behavior:
Even though it starts making backups I never managed to create a single working backup, because I have got many apps (more than 500) installed on my phone and after some time (every time different) always some little error happens and Seedvault stops the complete backup process. If I then restart the backup it deletes the whole unfinished backup from my Nextcloud server and starts all over.

Expected behaviour:
Seedvault should create separate backups app by app instead of creating one huge backup and breaking up after 10-40% because of a network error or even just a timeout. It should skip an app if creating a backup fails instead of breaking. stopping the complete backup process. Seedvault should restart where it left off instead of starting all over when it stopped for any reason.

Thanks in advance. If there is any additional information i can provide I'd be happy to, although I am not a developer (yet).

**Comment by grote** [comment]
Can you try doing a backup to a usb flash drive instead and see if that has the same problem? I suspect that you are hitting known issues with Nextcloud that are more likely to happen the more you have to back up. See #95 and #96

Note that Seedvault for Android 10 is not supported anymore (at least not by me).

**Comment by chirayudesai** [comment]
Another thing is, which version of the Nextcloud app are you using? 3.14 is what has the improvements @grote - so make it's that or higher for a start.

**Comment by grote** [comment]
Someone wanting to improve the "deletes the whole unfinished backup" issue for Android 10 could look into backporting some of the fixes from https://github.com/seedvault-app/seedvault/pull/151, specifically:

* 7401ead553cded3432b91c966ebb027597a20988
* 0a2131e10832de19710a6d18ec3fb4eb4fe657db
* 141fe7575d08a68346d7127a8a7c5fd1d37642ec
* e2f0d19f77cd8b25c463f9483ff47edc8cd68507 (most relevant)
* 82048f27541186c034aaf5f5bea7f203258be26a
* f5e9c30d1776a269747998a0cdf96524e47e585f

**Comment by EmanuelLoos** [comment]
Thank you for your reply.

I should have mentioned that I tried it with both Nextcloud (Version 3.14.0) and Nextcloud Dev (Version 20201127) using two different webservers, Hiawatha (clarnet) and Apache (hidden service over tor), and always had the same problem which I'd like to elaborate on a bit more now:

First I think my Issue mostly isn't about an specific error in Seedvault or Nextcloud (of course if it turns out to be one then it is also) but more about Seedvault's handling of (network) errors:

When I start a backup in any of the above setups it first works very well uploading everything to the cloud. However I never got any backup finished because with a backup this huge (I think) the possibility of a slow or lost wifi connection for a few seconds causing a single upload to timeout and fail becomes reality.

Right now Seedvault creates one huge backup process and if it fails (because e.g. you are using wifi and you get a timeout or whatever) then you have to restart the whole backup all over. I'd like Seedvault to handle each app backup as a separate process on a queue and remember which apps where already backed up.

I am quite sure backing up to a USB-Stick would work very well because this is more stable then the network.

If Android 10 is not supported anymore and these error handling problems are already fixed in the Android 11 this is no problem for me. After all my phone is rooted and when I flashed this unofficial LineageOS build it first didn't come with Seedvault which was added by an unofficial OTA Update. I can also backup my phone manually as it is rooted, Seedvault would just simplify the process for me so it would be a nice feature when it works with a cloud storage. I will look up for an Android 11 LineageOS build which works for my phone.

Sorry for how much I wrote!

**Comment by grote** [comment]
> Right now Seedvault creates one huge backup process and if it fails (because e.g. you are using wifi and you get a timeout or whatever) then you have to restart the whole backup all over.

That's not Seedvault, but the Android API we are using. There's not really a way around this.

> I'd like Seedvault to handle each app backup as a separate process on a queue and remember which apps where already backed up.

I'd like that as well, but you need to make Google change their API.

> How ever if Android 10 is not supported anymore and these error handling problems are already fixed in the Android 11 this is no problem for me.

What is fixed is how we report back to the Android API when a special system package fails. We need to fake that it succeeded in order to make the Android backup API from deleting the entire backup. So on the next backup run not all packages will get backed up again, but some will.

**Comment by grote** [comment]
Related to #102
