### ISSUE TITLE
Is it possible to change the backup quota?

### ISSUE THREAD

**Issue by jnnkB** [seedvault-app/seedvault#183]
Hi,

thanks a lot for all your work on this awesome project. I have a small problem: Some of my apps aren't backed up because they exceed the Backup quota. I unfortunately didn't find further information about this quota. Is it possible to change it. I don't really have a problem with large backups since I use a usb flash drive as my backup location.

**Comment by beerisgood** [comment]
This is e.g. the case for Aurora Store

**Comment by kjssad** [comment]
[I think the quota is 50MiB, if I'm not mistaken.](https://github.com/seedvault-app/seedvault/blob/4906a00786012ac638cd89de8549c2bb3b9579e6/app/src/main/java/com/stevesoltys/seedvault/transport/backup/FullBackup.kt#L31) It will be helpful to allow changes to the quota as I also generally backup files to an external drive.

**Comment by grote** [comment]
This sounds more like a question for [Discussions](https://github.com/seedvault-app/seedvault/discussions) than an issue to me.

The official backup limit of 25 MB is [well documented](https://developer.android.com/guide/topics/data/backup#Choosing). If an app is exceeding this, it is a bug of that app and it fails to exclude some of its internal data from backup. You should open issues with the respective app that is above quota, like I did [here for example](https://gitlab.com/gateship-one/malp/-/issues/214).
My guess for Aurora is that it also backs up the APKs that it downloaded which isn't necessary.

Seedvault already doubles the official quotas, but if an app is exceeding this, it seriously needs to consider what it backs up as their backup won't work on most phones. Giving users a way to set the quota doesn't make too much sense as the apps won't know which quota to target. This is just not how backup on Android works.

**Comment by jnnkB** [comment]
Ok thanks a lot for this explaination. I'm sorry, I didn't exect such a hard limit.

**Comment by benutzer74** [comment]
> The official backup limit of 25 MB is [well docume

Is this a Seedvault limit?
Does this mean, an app is never allowed to be bigger?
Or can an app be bigger, but will just not get backed up?

**Comment by grote** [comment]
> Is this a Seedvault limit?

No, please read
https://github.com/seedvault-app/seedvault/issues/183#issuecomment-748931399 again

> Does this mean, an app is never allowed to be bigger?

This is about app data, not the app's APK. They can try to backup more data, but on phones with Google Play services, the backup will fail.

> Or can an app be bigger, but will just not get backed up?

This.

**Comment by hrehfeld** [comment]
Ugh, this Android limit makes backup useless for the most important apps: gps log and other tracking data, photos, messenger, mail, ...

Is there any sort of workaround that seedvault could add?

**Comment by LuccoJ** [comment]
I personally don't give a darn if backups on phones with Google Play fail. I don't use them. I use other stuff for a reason, including ignoring unhelpful restrictions. Doubt Gadgetbridge (for instance) will allow backing up its data, even with assurances that they can indicate they require encryption, if I tell that once its database is over a certain size, the backup won't work, and they are to expect user support inquiries as to why.

**Comment by chirayudesai** [comment]
There has been a "Expert Setting" in the menu to ignore the quota for a while.

**Comment by LuccoJ** [comment]
@chirayudesai I had interpreted that one as the quota for overall backup size, specifically assuming that it would make incremental backups but at some point it would discard the older ones, and this quota related to that.

I know now (including from conversations with you) that this doesn't actually happen, but it's the reason why I originally disregarded that setting. I can't honestly tell whether that's an easy mistake for anyone to make, or it's just me... but it warns you that disabling it may "quickly fill your storage", and I think that contributed to me thinking it wasn't about individual applications.

FWIW, HTH, etc...

**Comment by chirayudesai** [comment]
Happy to accept string improvements!

The error when app is too big:
https://github.com/seedvault-app/seedvault/blob/android13/app/src/main/res/values/strings.xml#L159

The setting:
https://github.com/seedvault-app/seedvault/blob/android13/app/src/main/res/values/strings.xml#L51

**Comment by LuccoJ** [comment]
What about "(An) app exceeded its backup quota", although it's a bit more verbose than the original, and to make it look like "headline English" (or "error English"?) you can remove the "an" but you can't remove the "its" as that's the primary cue, and for the option, simply "Do not impose a limitation on the size of an app's backup.\n\nWarning: This can fill up your storage location quickly. Not needed for most apps."?
