### ISSUE TITLE
.backup.metadata fails to upload to nextcloud

### ISSUE THREAD

**Issue by besendorf** [seedvault-app/seedvault#184]
I am using seedvault with GrapheneOS and realized that the file `.backup.metadata` is not uploading to my nextcloud. Im not sure if this is an error from nextcloud or seedvault.
Here is the corresponding issue at the nextcloud repo:
https://github.com/nextcloud/android/issues/7696

**Comment by grote** [comment]
Does it fail to upload every time or is this only happening sometimes? Note that the metadata gets updated after every app, so failures are more likely to occur for that file.

Did you check the Uploads UI in the nextcloud app, if another upload attempt wasn't successfully made for that file? Is it still shown as failed there?

In general, I am quite sure that this is a Nextcloud issue as Seedvault uses the Storage Access Framework and there's not much we can do about how Nextcloud is implementing this.

**Comment by besendorf** [comment]
It fails everytime and its only the metadata fail, no other uploads fail. When I resume the uploadin the Nextcloud app it fails again. A friend of mine has the same issue with seedvault.
Heres a screenshot:
![1024-2219](https://user-images.githubusercontent.com/26350155/103091135-78bdb480-45f3-11eb-89a3-66571e55f15c.png)

**Comment by OliveiraHermogenes** [comment]
Just stopping by to write that this may be something particular to your setup, rather than a bug on either SeedVault or Nextcloud. I can't reproduce it here. LineageOS 17.1 (Android 10). Nextcloud Server 20.0.4. Nextcloud App 3.14.1.

**Comment by hmenke** [comment]
I'm seeing what I believe is a similar error.  Here is the relevant log entry on my server
```
{"reqId":"gL6ckWwYl7i4eL4OPntU","level":3,"time":"2021-01-09T01:38:34+00:00","remoteAddr":"XXX.YYY.ZZZ.000","user":"henri","app":"no app in context","method":"PUT","url":"/remote.php/webdav/.SeedVaultAndroidBackup/1606466854389/.backup.metadata","message":"{\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\BadRequest\",\"Message\":\"Expected filesize of 13964 bytes but read (from Nextcloud client) and wrote (to Nextcloud storage) 8192 bytes. Could either be a network problem on the sending side or a problem writing to the storage on the server side.\",\"Code\":0,\"Trace\":[{\"file\":\"/nix/store/6b27sl1g2lnm7a63njm2najvpkw8s0l3-nextcloud-20.0.4/3rdparty/sabre/dav/lib/DAV/Server.php\",\"line\":1143,\"function\":\"put\",\"class\":\"OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File\",\"type\":\"->\"},{\"file\":\"/nix/store/6b27sl1g2lnm7a63njm2najvpkw8s0l3-nextcloud-20.0.4/3rdparty/sabre/dav/lib/DAV/CorePlugin.php\",\"line\":515,\"function\":\"updateFile\",\"class\":\"Sabre\\\\DAV\\\\Server\",\"type\":\"->\",\"args\":[\"*** sensitive parameters replaced ***\"]},{\"file\":\"/nix/store/6b27sl1g2lnm7a63njm2najvpkw8s0l3-nextcloud-20.0.4/3rdparty/sabre/event/lib/WildcardEmitterTrait.php\",\"line\":89,\"function\":\"httpPut\",\"class\":\"Sabre\\\\DAV\\\\CorePlugin\",\"type\":\"->\"},{\"file\":\"/nix/store/6b27sl1g2lnm7a63njm2najvpkw8s0l3-nextcloud-20.0.4/3rdparty/sabre/dav/lib/DAV/Server.php\",\"line\":474,\"function\":\"emit\",\"class\":\"Sabre\\\\DAV\\\\Server\",\"type\":\"->\"},{\"file\":\"/nix/store/6b27sl1g2lnm7a63njm2najvpkw8s0l3-nextcloud-20.0.4/3rdparty/sabre/dav/lib/DAV/Server.php\",\"line\":251,\"function\":\"invokeMethod\",\"class\":\"Sabre\\\\DAV\\\\Server\",\"type\":\"->\"},{\"file\":\"/nix/store/6b27sl1g2lnm7a63njm2najvpkw8s0l3-nextcloud-20.0.4/3rdparty/sabre/dav/lib/DAV/Server.php\",\"line\":319,\"function\":\"start\",\"class\":\"Sabre\\\\DAV\\\\Server\",\"type\":\"->\"},{\"file\":\"/nix/store/6b27sl1g2lnm7a63njm2najvpkw8s0l3-nextcloud-20.0.4/apps/dav/appinfo/v1/webdav.php\",\"line\":84,\"function\":\"exec\",\"class\":\"Sabre\\\\DAV\\\\Server\",\"type\":\"->\"},{\"file\":\"/nix/store/6b27sl1g2lnm7a63njm2najvpkw8s0l3-nextcloud-20.0.4/remote.php\",\"line\":167,\"args\":[\"/nix/store/6b27sl1g2lnm7a63njm2najvpkw8s0l3-nextcloud-20.0.4/apps/dav/appinfo/v1/webdav.php\"],\"function\":\"require_once\"}],\"File\":\"/nix/store/6b27sl1g2lnm7a63njm2najvpkw8s0l3-nextcloud-20.0.4/apps/dav/lib/Connector/Sabre/File.php\",\"Line\":246,\"CustomMessage\":\"--\"}","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.14.1","version":"20.0.4.0"}
```
For better readability, here the extracted error message
```js
{
  "Exception": "Sabre\\DAV\\Exception\\BadRequest",
  "Message": "Expected filesize of 13964 bytes but read (from Nextcloud client) and wrote (to Nextcloud storage) 8192 bytes. Could either be a network problem on the sending side or a problem writing to the storage on the server side.",
  "Code": 0,
  "Trace": [
    {
      "file": "/nix/store/6b27sl1g2lnm7a63njm2najvpkw8s0l3-nextcloud-20.0.4/3rdparty/sabre/dav/lib/DAV/Server.php",
      "line": 1143,
      "function": "put",
      "class": "OCA\\DAV\\Connector\\Sabre\\File",
      "type": "->"
    },
    {
      "file": "/nix/store/6b27sl1g2lnm7a63njm2najvpkw8s0l3-nextcloud-20.0.4/3rdparty/sabre/dav/lib/DAV/CorePlugin.php",
      "line": 515,
      "function": "updateFile",
      "class": "Sabre\\DAV\\Server",
      "type": "->",
      "args": [
        "*** sensitive parameters replaced ***"
      ]
    },
    {
      "file": "/nix/store/6b27sl1g2lnm7a63njm2najvpkw8s0l3-nextcloud-20.0.4/3rdparty/sabre/event/lib/WildcardEmitterTrait.php",
      "line": 89,
      "function": "httpPut",
      "class": "Sabre\\DAV\\CorePlugin",
      "type": "->"
    },
    {
      "file": "/nix/store/6b27sl1g2lnm7a63njm2najvpkw8s0l3-nextcloud-20.0.4/3rdparty/sabre/dav/lib/DAV/Server.php",
      "line": 474,
      "function": "emit",
      "class": "Sabre\\DAV\\Server",
      "type": "->"
    },
    {
      "file": "/nix/store/6b27sl1g2lnm7a63njm2najvpkw8s0l3-nextcloud-20.0.4/3rdparty/sabre/dav/lib/DAV/Server.php",
      "line": 251,
      "function": "invokeMethod",
      "class": "Sabre\\DAV\\Server",
      "type": "->"
    },
    {
      "file": "/nix/store/6b27sl1g2lnm7a63njm2najvpkw8s0l3-nextcloud-20.0.4/3rdparty/sabre/dav/lib/DAV/Server.php",
      "line": 319,
      "function": "start",
      "class": "Sabre\\DAV\\Server",
      "type": "->"
    },
    {
      "file": "/nix/store/6b27sl1g2lnm7a63njm2najvpkw8s0l3-nextcloud-20.0.4/apps/dav/appinfo/v1/webdav.php",
      "line": 84,
      "function": "exec",
      "class": "Sabre\\DAV\\Server",
      "type": "->"
    },
    {
      "file": "/nix/store/6b27sl1g2lnm7a63njm2najvpkw8s0l3-nextcloud-20.0.4/remote.php",
      "line": 167,
      "args": [
        "/nix/store/6b27sl1g2lnm7a63njm2najvpkw8s0l3-nextcloud-20.0.4/apps/dav/appinfo/v1/webdav.php"
      ],
      "function": "require_once"
    }
  ],
  "File": "/nix/store/6b27sl1g2lnm7a63njm2najvpkw8s0l3-nextcloud-20.0.4/apps/dav/lib/Connector/Sabre/File.php",
  "Line": 246,
  "CustomMessage": "--"
}
```

**Comment by grote** [comment]
This *could* mean that Nextcloud has a bug to update the expected file size, when we upload a file more than once and the file size changes in the subsequent invocations.

**Comment by besendorf** [comment]
Im not entirely sure if it is a bug with nextcloud. Unfortunatly my issue at the nextcloud repo was closed. https://github.com/nextcloud/android/issues/7696
This error happens only with that one specific file though. Maybe you could look further into this @grote and comment on the nextcloud issue?

I also opened a thread here as the nextcloud developers asked me to.
https://help.nextcloud.com/t/specific-file-always-fails-to-upload/103784

**Comment by Dopeelf** [comment]
I am having this same issue. It seems the only file that is a problem is the metadata file. Would it be a viable workaround to store that file locally until the backup is finished and then upload it?

From my log file:
[no app in context] Error: Sabre\DAV\Exception\BadRequest: Expected filesize of 10317 bytes but read (from Nextcloud client) and wrote (to Nextcloud storage) 4096 bytes. Could either be a network problem on the sending side or a problem writing to the storage on the server side. at <<closure>>

0. /usr/local/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 1143
   OCA\DAV\Connector\Sabre\File->put(null)
1. /usr/local/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 515
   Sabre\DAV\Server->updateFile("*** sensitive parameters replaced ***")
2. /usr/local/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php line 89
   Sabre\DAV\CorePlugin->httpPut(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})
3. /usr/local/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 474
   Sabre\DAV\Server->emit("method:PUT", [Sabre\HTTP\Requ ... }])
4. /usr/local/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 251
   Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})
5. /usr/local/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 319
   Sabre\DAV\Server->start()
6. /usr/local/www/nextcloud/apps/dav/appinfo/v1/webdav.php line 84
   Sabre\DAV\Server->exec()
7. /usr/local/www/nextcloud/remote.php line 167
   require_once("/usr/local/www/ ... p")

PUT /remote.php/webdav/.SeedVaultAndroidBackup/1616245265934/.backup.metadata
from xxx.xxx.xxx.xxx by UserName at 2021-03-27T02:42:28+01:00

**Comment by Flunkyball** [comment]
Iam seeing the same here.
LOS 17.1, NC 20.0.8, App 3.15.1

**Comment by PeterBeu** [comment]
Same issue here, always .backup.metadata I've never had any other sync conflict.
LineageOS 18.1

**Comment by RobertWi** [comment]
> Same issue here, always .backup.metadata I've never had any other sync conflict.
> LineageOS 18.1

i concur 
NC client 3.16.0
Lineageos 18.1
Would be awesome tot be able to use this with NC. 
Option tot be able to select a dir as well

**Comment by exaveal** [comment]
Same problem here on several LOS 18.1 phones using Seedvault with Nextcloud .
First backup is working. Then you always get upload errors:
![photo_2021-07-23_13-34-04](https://user-images.githubusercontent.com/21370398/126776230-f57970ba-148e-46fb-8075-14677123e3d4.jpg)

First problem is that Nextcloud asks the user. The backup procedure is triggered by Seedvault - so there shouldn't be any user interactions necessary. Seedvault must answer this questions.
Second problem is, that even answering these questions doesn't solve the problem and the user gets the notification including the question again.

I'm not able to say if it is a bug of Nextcloud Server, Nextcloud Android Client or Seedvault.
Also I'm not able to say if backups with Seedvault & Nextcloud work at all. Because if only the first time the file is uploaded, than the you will make big eyes when you restore your backup and it's the version which was uploaded the first time. Meaning all changes done after the first upload are gone. Then there should be a big warning to the community to NOT USE Seedvault together with Nextcloud.

**Comment by mshavliuk** [comment]
I've just bumped into the same problem. Based on NC logs it looks like the NextCloud having troubles with saving `.backup.metadata` file and returning `500 server error`:
```json
[
  {
    "reqId": "SeCrEtXXX",
    "level": 3,
    "time": "2021-08-10T06:12:19+00:00",
    "remoteAddr": "1.2.3.4",
    "user": "User",
    "app": "PHP",
    "method": "PUT",
    "url": "/remote.php/webdav/.SeedVaultAndroidBackup/1628570565282/.backup.metadata",
    "message": {
      "Exception": "Error",
      "Message": "file_put_contents(/var/www/html/data/User/files/.SeedVaultAndroidBackup/1628570565282/.backup.metadata): failed to open stream: Permission denied at /var/www/html/lib/private/Files/Storage/Local.php#282",
      "Code": 0,
      "Trace": [
        {
          "function": "onError",
          "class": "OC\\Log\\ErrorHandler",
          "type": "::",
          "args": [
            2,
            "file_put_contents(/var/www/html/data/User/files/.SeedVaultAndroidBackup/1628570565282/.backup.metadata): failed to open stream: Permission denied",
            "/var/www/html/lib/private/Files/Storage/Local.php",
            282,
            {
              "path": "files/.SeedVaultAndroidBackup/1628570565282/.backup.metadata",
              "data": null,
              "oldMask": 18
            }
          ]
        },
        {
          "file": "/var/www/html/lib/private/Files/Storage/Local.php",
          "line": 282,
          "function": "file_put_contents",
          "args": [
            "/var/www/html/data/User/files/.SeedVaultAndroidBackup/1628570565282/.backup.metadata",
            null
          ]
        },
        {
          "file": "/var/www/html/lib/private/Files/Storage/Local.php",
          "line": 570,
          "function": "file_put_contents",
          "class": "OC\\Files\\Storage\\Local",
          "type": "->",
          "args": [
            "files/.SeedVaultAndroidBackup/1628570565282/.backup.metadata",
            null
          ]
        },
        {
          "file": "/var/www/html/lib/private/Files/Storage/Wrapper/Wrapper.php",
          "line": 629,
          "function": "writeStream",
          "class": "OC\\Files\\Storage\\Local",
          "type": "->",
          "args": [
            "files/.SeedVaultAndroidBackup/1628570565282/.backup.metadata",
            null,
            "*** sensitive parameter replaced ***"
          ]
        },
        {
          "file": "/var/www/html/apps/dav/lib/Connector/Sabre/File.php",
          "line": 207,
          "function": "writeStream",
          "class": "OC\\Files\\Storage\\Wrapper\\Wrapper",
          "type": "->",
          "args": [
            "files/.SeedVaultAndroidBackup/1628570565282/.backup.metadata",
            null
          ]
        },
        {
          "file": "/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php",
          "line": 1137,
          "function": "put",
          "class": "OCA\\DAV\\Connector\\Sabre\\File",
          "type": "->",
          "args": [
            null
          ]
        },
        {
          "file": "/var/www/html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php",
          "line": 492,
          "function": "updateFile",
          "class": "Sabre\\DAV\\Server",
          "type": "->",
          "args": [
            "*** sensitive parameters replaced ***"
          ]
        },
        {
          "file": "/var/www/html/3rdparty/sabre/event/lib/WildcardEmitterTrait.php",
          "line": 89,
          "function": "httpPut",
          "class": "Sabre\\DAV\\CorePlugin",
          "type": "->",
          "args": [
            {
              "__class__": "Sabre\\HTTP\\Request"
            },
            {
              "__class__": "Sabre\\HTTP\\Response"
            }
          ]
        },
        {
          "file": "/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php",
          "line": 472,
          "function": "emit",
          "class": "Sabre\\DAV\\Server",
          "type": "->",
          "args": [
            "method:PUT",
            [
              {
                "__class__": "Sabre\\HTTP\\Request"
              },
              {
                "__class__": "Sabre\\HTTP\\Response"
              }
            ]
          ]
        },
        {
          "file": "/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php",
          "line": 253,
          "function": "invokeMethod",
          "class": "Sabre\\DAV\\Server",
          "type": "->",
          "args": [
            {
              "__class__": "Sabre\\HTTP\\Request"
            },
            {
              "__class__": "Sabre\\HTTP\\Response"
            }
          ]
        },
        {
          "file": "/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php",
          "line": 321,
          "function": "start",
          "class": "Sabre\\DAV\\Server",
          "type": "->",
          "args": []
        },
        {
          "file": "/var/www/html/apps/dav/appinfo/v1/webdav.php",
          "line": 84,
          "function": "exec",
          "class": "Sabre\\DAV\\Server",
          "type": "->",
          "args": []
        },
        {
          "file": "/var/www/html/remote.php",
          "line": 167,
          "args": [
            "/var/www/html/apps/dav/appinfo/v1/webdav.php"
          ],
          "function": "require_once"
        }
      ],
      "File": "/var/www/html/lib/private/Log/ErrorHandler.php",
      "Line": 92,
      "CustomMessage": "--"
    },
    "userAgent": "Mozilla/5.0 (Android) Nextcloud-android/3.16.1",
    "version": "21.0.3.1"
  },
  {
    "reqId": "SeCrEtXXX",
    "level": 4,
    "time": "2021-08-10T06:12:19+00:00",
    "remoteAddr": "1.2.3.4",
    "user": "User",
    "app": "webdav",
    "method": "PUT",
    "url": "/remote.php/webdav/.SeedVaultAndroidBackup/1628570565282/.backup.metadata",
    "message": {
      "Exception": "Sabre\\DAV\\Exception",
      "Message": "Error while copying file to target location (copied bytes: -1, expected filesize: 157 )",
      "Code": 0,
      "Trace": [
        {
          "file": "/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php",
          "line": 1137,
          "function": "put",
          "class": "OCA\\DAV\\Connector\\Sabre\\File",
          "type": "->",
          "args": [
            null
          ]
        },
        {
          "file": "/var/www/html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php",
          "line": 492,
          "function": "updateFile",
          "class": "Sabre\\DAV\\Server",
          "type": "->",
          "args": [
            "*** sensitive parameters replaced ***"
          ]
        },
        {
          "file": "/var/www/html/3rdparty/sabre/event/lib/WildcardEmitterTrait.php",
          "line": 89,
          "function": "httpPut",
          "class": "Sabre\\DAV\\CorePlugin",
          "type": "->",
          "args": [
            {
              "__class__": "Sabre\\HTTP\\Request"
            },
            {
              "__class__": "Sabre\\HTTP\\Response"
            }
          ]
        },
        {
          "file": "/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php",
          "line": 472,
          "function": "emit",
          "class": "Sabre\\DAV\\Server",
          "type": "->",
          "args": [
            "method:PUT",
            [
              {
                "__class__": "Sabre\\HTTP\\Request"
              },
              {
                "__class__": "Sabre\\HTTP\\Response"
              }
            ]
          ]
        },
        {
          "file": "/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php",
          "line": 253,
          "function": "invokeMethod",
          "class": "Sabre\\DAV\\Server",
          "type": "->",
          "args": [
            {
              "__class__": "Sabre\\HTTP\\Request"
            },
            {
              "__class__": "Sabre\\HTTP\\Response"
            }
          ]
        },
        {
          "file": "/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php",
          "line": 321,
          "function": "start",
          "class": "Sabre\\DAV\\Server",
          "type": "->",
          "args": []
        },
        {
          "file": "/var/www/html/apps/dav/appinfo/v1/webdav.php",
          "line": 84,
          "function": "exec",
          "class": "Sabre\\DAV\\Server",
          "type": "->",
          "args": []
        },
        {
          "file": "/var/www/html/remote.php",
          "line": 167,
          "args": [
            "/var/www/html/apps/dav/appinfo/v1/webdav.php"
          ],
          "function": "require_once"
        }
      ],
      "File": "/var/www/html/apps/dav/lib/Connector/Sabre/File.php",
      "Line": 236,
      "CustomMessage": "--"
    },
    "userAgent": "Mozilla/5.0 (Android) Nextcloud-android/3.16.1",
    "version": "21.0.3.1"
  },
  {
    "reqId": "SeCrEtXXX",
    "level": 3,
    "time": "2021-08-10T06:12:19+00:00",
    "remoteAddr": "1.2.3.4",
    "user": "User",
    "app": "PHP",
    "method": "PUT",
    "url": "/remote.php/webdav/.SeedVaultAndroidBackup/1628570565282/.backup.metadata",
    "message": {
      "Exception": "Error",
      "Message": "Cannot modify header information - headers already sent by (output started at /var/www/html/3rdparty/sabre/http/lib/Sapi.php:132) at /var/www/html/apps/dav/lib/Connector/Sabre/File.php#691",
      "Code": 0,
      "Trace": [
        {
          "function": "onError",
          "class": "OC\\Log\\ErrorHandler",
          "type": "::",
          "args": [
            2,
            "Cannot modify header information - headers already sent by (output started at /var/www/html/3rdparty/sabre/http/lib/Sapi.php:132)",
            "/var/www/html/apps/dav/lib/Connector/Sabre/File.php",
            691,
            {
              "string": "X-Hash-SHA256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
            }
          ]
        },
        {
          "file": "/var/www/html/apps/dav/lib/Connector/Sabre/File.php",
          "line": 691,
          "function": "header",
          "args": [
            "X-Hash-SHA256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
          ]
        },
        {
          "file": "/var/www/html/apps/dav/lib/Connector/Sabre/File.php",
          "line": 195,
          "function": "header",
          "class": "OCA\\DAV\\Connector\\Sabre\\File",
          "type": "->",
          "args": [
            "X-Hash-SHA256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
          ]
        },
        {
          "function": "OCA\\DAV\\Connector\\Sabre\\{closure}",
          "class": "OCA\\DAV\\Connector\\Sabre\\File",
          "type": "->",
          "args": [
            "*** sensitive parameters replaced ***"
          ]
        },
        {
          "file": "/var/www/html/lib/private/Files/Stream/HashWrapper.php",
          "line": 71,
          "function": "call_user_func",
          "args": [
            {
              "__class__": "Closure"
            },
            "*** sensitive parameter replaced ***"
          ]
        },
        {
          "file": "/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php",
          "line": 321,
          "function": "stream_close",
          "class": "OC\\Files\\Stream\\HashWrapper",
          "type": "->",
          "args": []
        },
        {
          "file": "/var/www/html/apps/dav/appinfo/v1/webdav.php",
          "line": 84,
          "function": "exec",
          "class": "Sabre\\DAV\\Server",
          "type": "->",
          "args": []
        },
        {
          "file": "/var/www/html/remote.php",
          "line": 167,
          "args": [
            "/var/www/html/apps/dav/appinfo/v1/webdav.php"
          ],
          "function": "require_once"
        }
      ],
      "File": "/var/www/html/lib/private/Log/ErrorHandler.php",
      "Line": 92,
      "CustomMessage": "--"
    },
    "userAgent": "Mozilla/5.0 (Android) Nextcloud-android/3.16.1",
    "version": "21.0.3.1"
  }
]
```

**Comment by RobertWi** [comment]
Happy to report that it works fine and consistently with 2 android devices  

NC server 21.0.4
NC Android APP  3.16.1
SeedVault 11-1.1
LineageOS 18.1 builddate 20210719 (Android 11) 

NC server 21.0.4
NC Android APP  3.16.1
SeedVault 11-1.1
LineageOS 18.1 builddate 20210627 (Android 11)

**Comment by Sgt-Nukem** [comment]
> Same problem here on several LOS 18.1 phones using Seedvault with Nextcloud 20.0.11.
> First backup is working. Then you always get upload errors:
> 
> First problem is that Nextcloud asks the user. The backup procedure is triggered by Seedvault - so there shouldn't be any user interactions necessary. Seedvault must answer these questions.
> Second problem is that even answering these questions doesn't solve the problem and the user gets the notification including the question again and again.
> 
> I'm not able to say if it is a bug of Nextcloud Server, Nextcloud Android Client or Seedvault.
> Also I'm not able to say if backups with Seedvault & Nextcloud work at all. Because if only with the first upload the file is saved on the Nextcloud Server, you will make big eyes when you restore your backup and only the first version is restored which was uploaded the first time. Meaning all changes done after the first upload are gone. Then there should be a big warning to the community to NOT USE Seedvault together with Nextcloud.


I got the same problem since flashing Lineage to my phone and trying to depend on Seedvault for backup instead of `adb commands`.

NC server 22.1.0
NC app 3.16.1
Seedvault Backup 11-1.1
LineageOS/microG 18.1 2021-05-07 (Android 11)

![image](https://user-images.githubusercontent.com/4144388/130779558-8801a975-5356-4b38-b92b-f9c238656b03.png)

For **_this specific file_** it always triggers an error and then a _"pick the one you want to keep"_ confirmation over and over and over again... _(there's 42 error notifications from NC because of that right now)_

As there is no way to tell NextCloud _"always use the last and current one"_ it is impossible for the Seedvault user to determine which one would be best to keep.

All other files seem to have been uploaded just fine - I see many `*.apk` files with varying sizes and some 2 gigs stored in NC for the `.SeedVaultAndroidBackup` directory.

A wild guess would be that the NC file system watcher triggered a file changed event and NC schedules another upload file job but at this point there may already be one running for this exact file (and even some more scheduled already).
So depending on NC's upload job scheduling execution there may be race conditions and an uncertainty (from NC's point-of-view) on which one is the newest.

If this is the case a simple mitigation from Seedvault would be a checkbox in the settings _"write metadata only after backup finished successfully"_.

**Comment by BOFH90** [comment]
Same here with Pixel 5 and CalyxOS
NC server 21.0.4
NC app 3.17.0
Seedvault Backup 11-2.1
CalyxOS 2.9.0 (Android 11)

**Comment by falisca** [comment]
Same here with Graphene Os. I encountered the problem on the first sync, right after the backup initialization on Nextcloud. Now every sync of .backup.metadata fails.

**Comment by simonsan** [comment]
@Sgt-Nukem "trying to depend on Seedvault for backup instead of `adb commands`"

I'm thinking of actually using a workaround like that due to Seedvault in combination with Nextcloud being a bit annoying to use:

- use Seedvault to Backup data locally
- then use [Syncthing](https://syncthing.net) to sync it either on an intermediate device from where Backups are uploaded centrally or sync it directly with Syncthing to a Server

**Comment by gartner2000** [comment]
I also facing this problem in LOS 19... It says That my nextcloud server is offline.. it is not.... my nextcload app is working fine.

**Comment by grote** [comment]
Maybe try the DavX5 app for backups to Nextcloud. In my experience it works better.

> It says That my nextcloud server is offline.. it is not.... my nextcload app is working fine.

Seedvault wouldn't say this. It sounds like a Nextcloud issue.

**Comment by besendorf** [comment]
> Maybe try the DavX5 app for backups to Nextcloud. In my experience it works better.
> 
> > It says That my nextcloud server is offline.. it is not.... my nextcload app is working fine.
> 
> Seedvault wouldn't say this. It sounds like a Nextcloud issue.

How would i use Davx5? Seedvault only supports the official Nextcloud App.
If seedvault would support arbitrary storage providers we could usw any sync App an protocol like sftp, samba, webdav etc.

**Comment by grote** [comment]
Seedvault supports any app properly supporting SAF, but needs to be whitelisted by the ROM. My ROM does have the DavX5 app whitelisted.

**Comment by ripsy85** [comment]
Same issue bere in Pixel 7 pro and nextcloud.
Other folders are uploading but backup keeps failing. I had it on for months (about 4 by now) and same thing everyday

**Comment by lecrackzor** [comment]
> Same issue bere in Pixel 7 pro and nextcloud. Other folders are uploading but backup keeps failing. I had it on for months (about 4 by now) and same thing everyday

Hey I was searching the same thing today and was successfully able to set up a working backup using the DAVx5 app. Its a little non-intuitive if its your first time (like mine) but this page is the only resource I used to figure it out myself. https://www.davx5.com/tested-with/nextcloud

I wish you luck.

**Comment by kontell** [comment]
I see the same behaviour as the OP.

I get no errors when the backup is run manually and see that backup.metadata gets uploaded once for every four backups.

When run automatically backup.metadata gets uploaded once for every two to four app backups, with Nextcloud giving multiple errors that backup.metadata cannot be found locally.

It seems that backup.metadata will often get overwritten and a new upload request given to Nextcloud before the file is uploaded. Hence, Nextcloud complains that it can't find the local file and logs the error.

**Comment by grote** [comment]
> It seems that backup.metadata will often get overwritten and a new upload request given to Nextcloud before the file is uploaded.

Yes, it often gets overwritten,  but the requests are made in the right order. It is just that Nextcloud isn't handling this properly. Please try DavX5 instead.

> I get no errors when the backup is run manually and see that backup.metadata gets uploaded once for every four backups.

That is not the expected behavior.

**Comment by mxraw** [comment]
> Yes, it often gets overwritten, but the requests are made in the right order. It is just that Nextcloud isn't handling this properly. Please try DavX5 instead.

This does not work. The error given by the 'WebDAV mount' method is *identical* to the 'Nextcloud' method.

From the remote server: 
> $ docker logs nextcloud-nc-1 | grep .backup.metadata
> xxx.xxx.xxx.xxx - xxxxx [xxx/xxx/xxx:xx:xx:xx +0000] "PUT /remote.php/dav/files/xxx/.SeedVaultAndroidBackup/1234567890/.backup.metadata HTTP/1.1" 403 1027 "-" "User/Agent String"

I agree with the OP, it is hard to tell who is to blame here but reading the bones I would blame the Nextcloud WebDAV implementation. This could be verified by using a different WebDAV implementation.

Regardless this leaves SeedVault in a nonfunctional state and this issue should not be closed.

What also does not work: Backup to local device and then uploading the local 
.SeedVaultAndroidBackup folder via the Nextcloud App results in the same error.

The only way I have found to make SeedVault work currently is to backup to local device and then use SyncThing to transport it to a PC and then work magic on that PC to do the actual upload to a secure location.

**Comment by kontell** [comment]
I decided to ignore the error and continue using Nextcloud.

I recently migrated to a new phone and the restore was perfect.

**Comment by exaveal** [comment]
Nice for you. Backup doesn't work safely. For a backup solution: No Go. Nextcloud + Seedvault + LOS: How you should NOT do it.

Really Pain in the Ass. Several major Versions, years are gone. No working solution. This will never work.
