### ISSUE TITLE
Calendar entries backup

### ISSUE THREAD

**Issue by stelkintatko** [seedvault-app/seedvault#194]
Greetings to all of you!
wanted to see a backup of all calendar entries currently found in the phone. Possibly, might be a great feature, to be able to select, which accounts (sources) of calendar records to backup. Of course - not much sense to backup something like exchange, so it would be duplicated after restore. Please consider it... Thank you.

**Comment by grote** [comment]
AFAIK it isn't possible to store calenders locally. If you use a sync calender backend like exchange or dav x5, the entries should get synced and not backed up. If you use a special app that allows you to store events locally, this app should take care of backup.
