### ISSUE TITLE
Call-log exemption only works on initial backup

### ISSUE THREAD

**Issue by chris42** [seedvault-app/seedvault#195]
Turning off the call-log backup in the backup options seems to only work for the initial backup (triggered manually). The following automatic backup then starts to back up the call-logs as well.

Tried this now twice and both times it happened.

**Comment by grote** [comment]
@t-m-w I think you tested backup excludes recently and there apps got excluded correctly, right?

**Comment by t-m-w** [comment]
> @t-m-w I think you tested backup excludes recently and there apps got excluded correctly, right?

Yes, this is likely just a UI issue/quirk. Here are parts of my [messages from the Matrix room](https://matrix.to/#/!cEwaALtjflVfstEGpG:matrix.org/$QwDBCcuSdlQrzD1U3IYZz98CyRZYxUPBVEbOOx7GSwc?via=calyx.dev&via=matrix.org&via=kde.org), 2022-05-31 (ET):

> It looks like the "Backup finished" notification tells you how many apps have ever been backed up, not how many were backed up last time -- or, at least, how many were successfully backed up + how many were backed up once but are now excluded. That is the behavior I'm seeing when I mess with exclusions, at least.

> I think it's working. I tried in a fresh work profile with everything toggled off except 1 thing, and it said it backed up 1 item. I added one more, ran again, it said it backed up 2. So then I removed the second one and ran again, it still said 2.

**Comment by grote** [comment]
> The following automatic backup then starts to back up the call-logs as well.

How do you know this? Does the time of the last backup in the app status list get updated? Can you provide screenshots?

**Comment by chris42** [comment]
phew... this is 3 years ago. I do not know anymore, how I figured it. I think it was the runtime it took and somewhere a status that they are now backed up.
Closing this, as I am not using seedvault anymore and can't contribute. If this is still an issue someone will pop up.
