### ISSUE TITLE
rclone as a backup location

### ISSUE THREAD

**Issue by jtagcat** [seedvault-app/seedvault#196]
[rclone](https://rclone.org) supports many, many backends. From Google Drive (#167) to SFTP (#173, #171) to Seafile (#84, #169). It has multiple programmatic interfaces available, also encryption, if you're in to that.

Downsides:
 - AFAIK, you can't use an account from the device, like you do with Nextcloud at the moment. You have to manually sign in. Pulling credentials might be possible, I haven't developed a ton for Android, so I can't say for sure.
 - The manual sign in is a CLI wizard. There are 3rd party open source things providing a GUI, though an in-house one could be created as well (directing the prompts in each step of the CLI to a GUI could work well enough).

Upsides:
 - Developer time. Adding a growing list of remotes. Maintainership, development, debugging, research of platform, time spent in issues.
   - The same time could go towards other features.
 - Allowing a vast range of destinations, that would be otherwise be impossible to maintain.

Related: #180 

### GitHub Etiquette

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by dotlambda** [comment]
This might be supported by https://github.com/x0b/rcx.

**Comment by Glutamat42** [comment]
I tried rcx, but i cannot select it as a target storage in seedvault.
I would appreciate rclone support because the nextcloud app seems to keep a local copy of the backup data. Especially in combination with local storage backup this is a huge problem for me.

**Comment by grote** [comment]
rclone is unlikely to be supported directly. If somebody ports it to Android, you could backup to local storage and use rclone to back that up.

**Comment by danielkrajnik** [comment]
+1 really useful is an understatement - an essential feature. Please someone help implement it
RCX doesn't have automatic backups (?!), the only solution right now are termux scripts (?!!), but that's such a niche technique

**Comment by grote** [comment]
This can now be used via Roundsync added in #609
