### ISSUE TITLE
Restore UX: Clarify 'Re-installing apps' stage

### ISSUE THREAD

**Issue by jtagcat** [seedvault-app/seedvault#202]
For a moment, you have a blank screen with a greyed out next button.

Then comes a random app, with a checkmark next to it. Slight panic, was only that app included in the backup? Am I selecting to restore that? The next button is still greyed out…

Additionally, the list sometimes just freezes for 10s. This causes doubt on whether something is happening, and should interruption be required. The user has probably tried pressing next, or clicking apps in the list a few times without any response now.

***

Eventually, the user probably makes sense of the situation, but I'd advise to:
 - Add a 'please wait' or something. Give indication, that 'go take a walk'
 - Add a progress bar, at the top probably. Currently, it's just a black box. e: initiated restore from adb, not fullscreened, noticed half way through, there is a tiny progress bar at the top.
 - Maybe remove the greyed out next button?

More comments:
 - Explain exclamation marks, failures. For instance, I'd guess F-Droid install failed due to it already being installed; perhaps even as a system app.
 - A cancel button? Instead of waiting for the process to finish, the user could choose another backup right away, or factory reset right away.

**Comment by jtagcat** [comment]
Related: #117

**Comment by rugk** [comment]
>  Give indication, that 'go take a walk'

As you have plenty of space, this is the perfect case for when an UI could show simple (greyish or so) placeholder images/illustrations. E.g. from https://undraw.co/search (search for "backup", "waiting", "meditation" or "apps", e.g.)

Something like having a coffee or so…

**Comment by grote** [comment]
@jtagcat did you try restore recently? Is it better now? There should be a progress bar.

**Comment by jtagcat** [comment]
I moved on to https://github.com/NeoApplications/Neo-Backup
