### ISSUE TITLE
Feature Request: Select backup folder for Nextcloud

### ISSUE THREAD

**Issue by renatobellotti** [seedvault-app/seedvault#205]
It would be nice if users could select the directory where the backup will be stored.

Use case:

I have added some HD storage as external storage to my Nextcloud. I would like to use this slow but cheap space instead of the more expensive SSD storage.

**Comment by grote** [comment]
Nextcloud is not allowing you to link your HDD or a folder on it to the folder that seedvault uses? If Nextcloud runs on Linux, you could use a symlink.

**Comment by grote** [comment]
otherwise, this looks like a duplicate of #143

**Comment by stevesoltys** [comment]
Closing since this is a duplicate.
