### ISSUE TITLE
12 words review later

### ISSUE THREAD

**Issue by stelkintatko** [seedvault-app/seedvault#207]
Hey gents,
how can i check the phrase, if it is still the same? I changed phone, tried to restore, did not work. So installed and started seedvault agian, but not sure of the 12 words... Is there a way to display the 12 words again in the phone to ensure i got the right set saved?

**Comment by chirayudesai** [comment]
You can't see the passphrase again, however you can re-enter it to verify from the next build onwards now that https://github.com/seedvault-app/seedvault/pull/168 has been merged.
