### ISSUE TITLE
0-size .backup.metadata corrupts backup in Nextcloud

### ISSUE THREAD

**Issue by hank** [seedvault-app/seedvault#211]
I ran into a bit of a panic situation today: I re-locked my bootloader, wiping the phone, and was looking forward to using seedvault to restore. I got all the way into the restore and it failed to find any backups on Nextcloud (uhoh). After looking into it some more, I found out that my .backup.metadata file was 0 length! Luckily I was able to restore it to a previous version in Nextcloud and start restoring from that. Please ensure that this file is never zeroed somehow. If for some reason I had file versioning off in Nextcloud (not sure if that's possible, but it might be), I'd be totally screwed. Could this have happened because of an ongoing backup when I shut off my phone for the last time?

**Comment by hank** [comment]
Also none of my app data restored, which is sad.

**Comment by grote** [comment]
Hi @hank, I am sorry your backup wasn't able to restore much. 

> Please ensure that this file is never zeroed somehow.

I wish we could. But we can just hand over data to Nextcloud and hope it uploads it properly. We can't even do this synchronously and get info back from Nextcloud (or other SAF providers) if the upload worked or not as Android's storage API doesn't allow this.

There's only so much we can do to fix Nextcloud itself. See https://github.com/seedvault-app/seedvault/issues/96 where we already did tons of work and also fixed a `0 byte` file issue.

> Also none of my app data restored, which is sad.

Sad indeed. Sorry. What did the UI show when it couldn't restore files? just error symbols everywhere? A logcat from this would be nice, also to know which versions of Seedvault and Nextcloud you were using.

**Comment by hank** [comment]
I wonder if the solution to the validation of the upload is to upload something like .backup.metadata.new, since it's only a few KB, then verify its contents before deleting .backup.metadata then renaming the new one. That way, you can almost guarantee the file won't be zeroed. Another solution would be to give us the option of keeping a certain number of full backups, maybe 1 day, 1 week, 1 month options. I have terabytes of space so I'm not worried about a few days of phone backups.

The UI showed success for almost every app once I got the restore rolling with the old metadata file - little checkmarks next to each one. Upon opening each one though it was like running for the first time. This was obviously a few days ago - anything I can pull at this point to help? I'm not really too excited about wiping my phone again since I just set it all back up.

Nextcloud version: 20.0.6

**Comment by grote** [comment]
> I wonder if the solution to the validation of the upload is to upload something like .backup.metadata.new, since it's only a few KB, then verify its contents before deleting .backup.metadata then renaming the new one.

That's a good idea if you are dealing with a normal file system or a sane storage API. Neither is the case here.

I haven't tried it, but I somehow doubt Nextcloud will handle the increased complexity of renaming a file that hasn't even been uploaded, yet. And like I said, we don't get notified when the upload finished as this happens async whenever Nextcloud gets to it. Our code might not even be running anymore when it happens.

The real solution is to write different storage plugins that don't use SAF to store backups.

> Another solution would be to give us the option of keeping a certain number of full backups

For now, you can manually re-set the Nextcloud storage in Seedvault. That should create a fresh backup.

> The UI showed success for almost every app once I got the restore rolling with the old metadata file - little checkmarks next to each one.

Was that for app re-install or data restore or both?

>  Upon opening each one though it was like running for the first time.

some apps report ok for restore, but don't actually restore relevant data, might also be this.

**Comment by bill-mcgonigle** [comment]
> I haven't tried it, but I somehow doubt Nextcloud will handle the increased complexity of renaming a file that hasn't even been uploaded, yet. And like I said, we don't get notified when the upload finished as this happens async whenever Nextcloud gets to it. Our code might not even be running anymore when it happens.

I was just looking at the current API and still don't see 'sync' options anywhere.  Wow, it's not FUSE.

Might SAF do the right thing if it gets a write/read for the same storage object?  Then wait on the read and just ignore it, then proceed?  I wasn't able to find any kind of description for ordering behavior in the docs (seems like thread-safety would demand it?).

**Comment by grote** [comment]
SAF allows writes to the same file from different *processes* and Nextcloud doesn't seem to be very smart to handle writes from just Seedvault to the same file.
