### ISSUE TITLE
Donate link?

### ISSUE THREAD

**Issue by whitequark** [seedvault-app/seedvault#219]
Seedvault is the first Android backup application that works the way I think it should. That's awesome! Is there a way to support the project?

**Comment by nickcalyx** [comment]
Hi !  Monetary donations are very welcome at https://members.calyxinstitute.org/donate !  We accept credit cards, several forms of crypto currency, checks, and wire transfers

You can also encourage people to become members of the Institute and get a mobile hotspot with unlimited/unthrottled/uncapped data ( in the US only )   see :  https://www.youtube.com/watch?v=hXmNk_PW4Q8

Code contributions are of course also more than welcome !

**Comment by whitequark** [comment]
Thanks! I'll donate there.
