### ISSUE TITLE
Backup Mobile Data and WiFi Permissions

### ISSUE THREAD

**Issue by bettyvschmartz** [seedvault-app/seedvault#224]
Because there is no bulk management of network access / firewall controls, I usually end up going through apps one-by-one and blocking all network access. From there I start allowing what I need. This is an inconvenience but is really only required at first set up. 

However, these settings are not backed up so on restore one must do it all over again. 

In the absence of global toggles it would be good to have these backed up. 

-- BVS

**Comment by grote** [comment]
@chirayudesai might know better, but this *sounds* like your Android ROM should include these settings in the respective app, probably settings app. This is not really a Seedvault issue, but of the app these settings come from.

**Comment by chirayudesai** [comment]
@Uldiniad was going to look into for LineageOS / CalyxOS / others using the same policy-based firewall rules.

Our current idea is that there's something storing this in the system to restore the Settings after a reboot so we'll try to back that up if possible. 

The application handling the toggles (Settings or Datura) does not keep any state currently, but if the above idea doesn't work we can change that instead then to back it up there.

**Comment by bettyvschmartz** [comment]
But all my other settings from the Settings are restored, it's only the permissions that aren't. Maybe the addition of the new Datura app fixes this. 

-- BVS

**Comment by bettyvschmartz** [comment]
> @Uldiniad was going to look into for LineageOS / CalyxOS / others using the same policy-based firewall rules.
> 
> Our current idea is that there's something storing this in the system to restore the Settings after a reboot so we'll try to back that up if possible. 
> 
> The application handling the toggles (Settings or Datura) does not keep any state currently, but if the above idea doesn't work we can change that instead then to back it up there.

OK, this makes sense now. Would be really useful so that an app isn't restored that then gets full network access, for example. 

-- BVS

**Comment by Uldiniad** [comment]
the system reads and writes to the following file `/data/system/netpolicy.xml`

**Comment by grote** [comment]
I guess this is owned by the system user, so maybe some system user app could include it in its backup? I wonder why AOSP doesn't handle this. Or is the addition of this file part of a non-upstream patch?

Btw. I consider this a non-Seedvault issue, but we can keep this ticket open, if it makes sense to discuss this here.

**Comment by chirayudesai** [comment]
This file does exist in AOSP. We'll look into what can access it and try to back it up accordingly - maybe in Settings or Datura or something else.

And yeah, this isn't a Seedvault issue, we can discuss it elsewhere but keep this open till this is implemented (just so we have something that users can see when reporting)

**Comment by Uldiniad** [comment]
https://gitlab.com/CalyxOS/calyxos/-/issues/384
https://review.calyxos.org/c/CalyxOS/platform_frameworks_base/+/3061
