### ISSUE TITLE
Saying backup failed to run

### ISSUE THREAD

**Issue by goswamiji321** [seedvault-app/seedvault#225]
![Screenshot_20210318-020738622](https://user-images.githubusercontent.com/74024807/111535087-bbc09b80-878e-11eb-886a-45c42fa8d2e5.jpg)
![Screenshot_20210318-020736776](https://user-images.githubusercontent.com/74024807/111535093-bcf1c880-878e-11eb-9981-a4d0de577802.jpg)

Using resurrection remix ROM
When I select nextcloud it shows initialising backup location and then shows "an error occurred when accessing the location" I use free 10 GB sprycloud nextcloud account and official nextcloud account app in my phone.

**Comment by Grimace780** [comment]
Also happening on my Motorola Moto g7 running LineageOS.

**Comment by schklom** [comment]
Try after using a VPN
