### ISSUE TITLE
Where is the backup file? Can I copy it to a server, and then back for restore?

### ISSUE THREAD

**Issue by peteforsyth** [seedvault-app/seedvault#228]
I was surprised I couldn't choose a FTP or SMB location that my phone's attached to for a backup location -- only internal memory. I want to wipe my OS, reinstall, and then restore apps. Is there any way to do this without NextCloud?

Can I manually copy the backup file to a server, and then move it back to the phone after reinstalling LineageOS?

**Comment by keks24** [comment]
See #127.

On my `OnePlus One (LineageOS 18.1, Android 11)` all backups are saved in `/sdcard/.SeedVaultAndroidBackup/`.
