### ISSUE TITLE
pCloud as a backup location with SAF

### ISSUE THREAD

**Issue by carlocastoldi** [seedvault-app/seedvault#229]
pCloud app should support SAF—Storage Access Framework—and it is indeed visible through system's File app (see screenshot below).
That said it seems like I cannot choose it as the destination of my backups.

OS: LineageOS 17.1
Phone: ZUK Z2 Plus

<details> 
<img src="https://user-images.githubusercontent.com/34198340/110217117-ab691080-7eb2-11eb-80f3-e2ffb3e9260a.jpg">
</details>

P.S. could it be linked to #167 and #169 ?

**Comment by grote** [comment]
Yeah, somebody has to test this and then LineageOS needs to white list this app for use with Seedvault.

Since it doesn't seem to be Free Software and it will be hard to make this app available for restore in setup wizard, I am skeptical about anyone whitelisting this.

**Comment by carlocastoldi** [comment]
I am quite new to this app, so I haven't seen its full behaviour. I don't have any other cloud options, but I would still like to detach from Google's backup system.
Could you please explain me the procedure I would need to follow if I wanted to make it whitelisted?

Do I really need the approval from LineageOS in order to use pCloud with SAF on **any** app?
From what I understand the problem is that the setup wizard of LineageOS's first boot should incorporate pCloud app _by default_ in order to support it. Am I right?
Isn't it possible to restore a backup **outside** of the setup wizard? After the user installed pCloud?

Also: pCloud supports WebDAV (https://webdav.pcloud.com/). Can it be somehow usefull?

**Comment by kuxv** [comment]
Why was it closed? Is it working now?

**Comment by grote** [comment]
pCloud seems to support WebDAV (can be used via DavX5 app) and SAF (needs whitelisted by ROM).
