### ISSUE TITLE
Restore crashes when restoring from nextcloud

### ISSUE THREAD

**Issue by lheckemann** [seedvault-app/seedvault#230]
If the Nextcloud app is backed up to Nextcloud using Seedvault and one tries to restore the backup, it will fail (restore screen just disappears after restoring a few other apps). As a workaround, the backup files for Nextcloud can be removed manually.

**Comment by grote** [comment]
Did you back up using Nextcloud as storage location as well or did you manually copy things to Nextcloud? In the latter case, this crash is expected and we should probably explicitly exclude Nextcloud if it is being used for restore this way.

**Comment by lheckemann** [comment]
Yes, I backed up to Nextcloud originally and tried restoring from there.

**Comment by grote** [comment]
That's strange as the expected behavior is that the Nextcloud app gets automatically excluded from backup when it is used to perform the backup, otherwise, it would get killed by the system when it fetches its data.

Is it possible that you backed up to a stable/beta/dev version and then used a different version for restore?

Do you happen to have a logcat log from when "restore screen just disappears after restoring a few other apps"?

**Comment by lheckemann** [comment]
I was following the logs, but didn't save them unfortunately :/ I'll see if I can reproduce this later, but I don't have a spare phone for testing.

**Comment by grote** [comment]
If you are still using Seedvault, you should be able to see the backup status of the Nextcloud app you use to save backups to.

Is it possible that you backed up to a stable/beta/dev version and then used a different version for restore?

**Comment by lheckemann** [comment]
I don't think so, I installed the default version from F-Droid in both cases, the restore was done the day after the backup, no new version of Nextcloud appeared on F-Droid on that date, and I generally install any updates right away… As said, I'll try and reproduce this with more information eventually and I'm fine with this being ignored until then :)

**Comment by grote** [comment]
should be finally solved by https://github.com/seedvault-app/seedvault/pull/422
