### ISSUE TITLE
Allow exporting the passphrase to a text file on generation

### ISSUE THREAD

**Issue by csolisr** [seedvault-app/seedvault#232]
While the mnemonic system of twelve random words is a great choice for security reasons, it's not so useful for the initial setup and latter recovery. For instance, it currently relies on either having a physical pen and paper (or a secondary digital device) to jot down the passphrase, or on memorizing the twelve random words in order (which not everyone can do reliably). This is especially conspicuous when the option to export the backups to the cloud is enabled, but still depends upon the user's memory, access to the specific paper where the passphrase was written to, or access to a secondary device. An option to export the passphrase to a text file that can be moved to safe storage, or to the cloud, could work as a reasonable compromise to prevent said passphrase from being accidentally lost by the user, even more so since the application doesn't offer the option to regenerate the twelve words in case of losing them in the first place.

**Comment by FlailAway** [comment]
Just do a screen capture, Vol-Up and Start, or maybe Vol-Dn and Start. Save that somewhere else.

**Comment by csolisr** [comment]
Good to know, I was wondering if Seedvault used the safety measure to prevent screenshots for privacy. But if they ever implement it, it'd be good to add a text backup option.

**Comment by grote** [comment]
A recent security audit re-iterated that there's specialized malware out there stealing BIP39 passphrases and asked us to prevent screenshots, so text export won't happen either. jotting 12 words down once isn't really too bad.

**Comment by csolisr** [comment]
> A recent security audit re-iterated that there's specialized malware out there stealing BIP39 passphrases and asked us to prevent screenshots, so text export won't happen either. jotting 12 words down once isn't really too bad.

Does the application allow to be open in split-screen mode to manually type the twelve words in a text file of our choice? Or does the security audit recommend disabling that as well for security reasons?

**Comment by daddy32** [comment]
This isn't good enough.
Password managers are current security best practice for use cases like this (as far as I am aware) and this process does not support them.
