### ISSUE TITLE
Only 10 words of recovery key are shown 

### ISSUE THREAD

**Issue by varac** [seedvault-app/seedvault#233]
I want to use seedvault on my Sony Xperia XA2 (LineageOS 18.1), but only 10 words of the recovery key are shown as you can see on the screenshot:

![Screenshot_20210404-141435_Seedvault](https://user-images.githubusercontent.com/488213/113508480-8cf94200-9550-11eb-8b0b-a10cec7442b0.png)

The same issue was also present before upgrading from LOS 17.1. Any ideas what's happening ?

**Comment by grote** [comment]
Seedvault was originally developed for devices with large displays for CalyxOS. Yours might be small or the font size might be ramped up quite a bit. 

Someone needs to review and fix the entire UI on small display devices. Help welcome!

**Comment by FlailAway** [comment]
Can you scroll up? That's what I do when keyboard covers the last 4 items. Might work.

**Comment by varac** [comment]
No I can't scroll up/down, I didn't find anything that would reveal all 12 words.

**Comment by DPTJKKVH** [comment]
In the Android display settings you can decrease text size. That might help.

If you enable the android hidden developer menu, you can change the screen resolution. If you increase that, everything gets scaled down (not only text). This way you should be able to see the hidden words.

Developer menu is enabled by going to the About section of your phone and tapping the build number tab quickly. (Up to ten times or so. It will count you down.) After that go back, go to system settings, advanced and then developer options.

**Comment by varac** [comment]
I guess I'll just wait until this bug is fixed properly.

**Comment by DirkSchmitt** [comment]
Same on a device with increased font size setting. 
Mitigation was the change the font size in the settings of the device.

**Comment by rugk** [comment]
Note to classify this correctly: This is an accessibility issue.

It always happens when you increase the font size. And decreasing it is of course only a workaround, as you may of course have reasons why you increased the font size, i.e. to be able to read that password there, actually.

Solutions:
* allow scrolling there
* or IMHO better: reduce the whitespace between the items/words/dynamically adjust it based on screen height. There is plenty of empty space there… :sweat_smile:

**Comment by rugk** [comment]
The "changelog", i.e. tag description for [v11-1.2](https://github.com/seedvault-app/seedvault/releases/tag/11-1.2) (cf. https://github.com/seedvault-app/seedvault/issues/292) seems to mention (fix?) this issue:
> * Make recovery code fit on smaller screens / larger densities

Friendly note to the maintainers: If you fix an issue, it's best to actually really link/mention the issue number, then GitHub would have linked that automatically.

**Comment by grote** [comment]
fixed in master
