### ISSUE TITLE
The Backup Message 'Waiting to Backup' is Confusing

### ISSUE THREAD

**Issue by bettyvschmartz** [seedvault-app/seedvault#234]
> side note: I find the waiting to backup message a little confusing after a backup is performed. I have noticed it happens in contacts for example when there are no contacts

Should this be raised as a separate issue? I also notice on backup completion the message `...waiting to backup` on both _Local Contacts_ and _SMS Messages_. I assume this is because I have cloud-based contacts (no local, device contacts) and have another default SMS app (native SMS app therefore has no messages).

Would it not be better to change to something like `Nothing to backup`?

-- BVS

_Originally posted by @bettyvschmartz in https://github.com/seedvault-app/seedvault/issues/152#issuecomment-814061908_

**Comment by bettyvschmartz** [comment]
As discussed, raising this as a separate issue to be fixed. The backup message `..waiting to backup` is confusing for those apps that have no data. Proposing something like `Nothing to backup` as more appropriate.

-- BVS

**Comment by grote** [comment]
> Proposing something like Nothing to backup as more appropriate.

I don't agree here, because the message just means that the system didn't ask us to back up something. There's a separate message for no data already.

**Comment by grote** [comment]
Also note that `Waiting to Backup` is the same language used by Google for this situation.

**Comment by bettyvschmartz** [comment]
> > Proposing something like Nothing to backup as more appropriate.
> 
> I don't agree here, because the message just means that the system didn't ask us to back up something. There's a separate message for no data already.

So in this case it's not `waiting to backup` in the backup run as nothing was requested to backup. So maybe another message you think is more appropriate but `waiting to backup` isn't accurate and is misleading for the user IMO. You've given some language above that explains it better so maybe `Not requested for backup`, `Excluded from Backup`, or `Backup skipped`. I think some users will believe either a) the backup didn't complete, or b) the backup still needs to finish as these apps are `waiting to backup`.

-- BVS

**Comment by chirayudesai** [comment]
> > Proposing something like Nothing to backup as more appropriate.
> 
> I don't agree here, because the message just means that the system didn't ask us to back up something. There's a separate message for no data already.

So let's just use that.

> Also note that `Waiting to Backup` is the same language used by Google for this situation.

We can do better :)


If there's no backup data keeping it always waiting for backup, we should show a different message, especially since these items are highlighted and shown at the top and thus the first things that a user would see.

**Comment by Rihcus** [comment]
I have had waiting to backup issues with google in the past. Adding a backup now button would be nice

**Comment by grote** [comment]
> >    There's a separate message for no data already.

> So let's just use that.

But that's a separate case. After turning on backup for the first time, all apps are "waiting for backup", but only some of those will be "no data" after the first run. So these really are two different cases and I am not sure how to present them better to the user.

**Comment by dehnhard** [comment]
Noticed this message and was glad to found this issue to be assured the backup went well.

The text message is a bit confusing, but the "warning icon" beside it makes the user wonder if he has to wait until it's finished or something has gone wrong. A green tick for these entities would be better.

**Comment by nandlab** [comment]
I have GrapheneOS with sandboxed Google Services. After a successful backup, Google Play Store, Maps and "Speech Recognition and Synthesis from Google" are showing "Waiting to back up...", which is confusing.
GmsCompatConfig and Google Play Services have a red exclamation mark, but maybe this is a different issue.

**Comment by DDvO** [comment]
I get the 'Waiting to Backup' outcome for around 75% of my apps
(and a backup error indication for a few further apps),
which seems to render Seedvault pretty useless :-(

Update: I opened an issue on this point: #684

**Comment by grote** [comment]
We are now asking the system to back up apps, so we choose which apps. That means the message "Waiting to backup" should only ever be shown before the first backup ran. If (on a recent version) it is shown afterwards this may indicate a bug and warrant a new ticket.

So far I haven't seen a suggestion on how to improve the "Waiting to backup" message.

**Comment by bettyvschmartz** [comment]
> So far I haven't seen a suggestion on how to improve the "Waiting to backup" message.

I guess it isn't clear to me what has been done here. If _the message "Waiting to backup"_ is now not shown after a backup runs it seems the issue is resolved. Unless you are now referring to the language "Waiting to backup" still showing before the first backup? In that case I don't personally see that as much of an issue as was previously the case. While still not strictly the correct wording, I expect the user will think to try kick off a backup. Whereas previously that message still showing after backup was much more confusing and problematic IMO. 

-- bvs

**Comment by dehnhard** [comment]
> We are now asking the system to back up apps, so we choose which apps. That means the message "Waiting to backup" should only ever be shown before the first backup ran. If (on a recent version) it is shown afterwards this may indicate a bug and warrant a new ticket.

Yes, I don't see this message anymore on any App. 
But it's still there on "local contacts".

> I guess it isn't clear to me what has been done here. If the message "Waiting to backup" is now not shown after a backup runs it seems the issue is resolved. Unless you are now referring to the language "Waiting to backup" still showing before the first backup? In that case I don't personally see that as much of an issue as was previously the case. While still not strictly the correct wording, I expect the user will think to try kick off a backup. Whereas previously that message still showing after backup was much more confusing and problematic IMO.

I agree.

**Comment by grote** [comment]
So it isn't the message that is confusing, but there are some bugs which leave this message appear longer than it should. 

> Yes, I don't see this message anymore on any App.
> But it's still there on "local contacts".

This for example was a bug which is fixed in https://github.com/seedvault-app/seedvault/commit/53b98ea0a95f975f786b2357231f2645e8e77675

So if, with the latest version, this still happens for apps, we should open a dedicated ticket for it and investigate.

> I don't personally see that as much of an issue as was previously the case. While still not strictly the correct wording

But what would be the correct wording?

**Comment by dehnhard** [comment]
> So it isn't the message that is confusing, but there are some bugs which leave this message appear longer than it should.

Sounds correct, but we users can't possibly know that.

> > Yes, I don't see this message anymore on any App.
> > But it's still there on "local contacts".
> 
> This for example was a bug which is fixed in [53b98ea](https://github.com/seedvault-app/seedvault/commit/53b98ea0a95f975f786b2357231f2645e8e77675)

Great. I notice that commit appears to be part of an open pull request and therefor it will be solved someday in the future.

**Comment by grote** [comment]
> Sounds correct, but we users can't possibly know that.

Right, but it still means the same thing, only that we are waiting forever and never get included in a backup. Unfortunately, not easy to know why. Also not for developers as this comes from the Android system.

> Great. I notice that commit appears to be part of an open pull request and therefor it will be solved someday in the future.

Right.

For the remaining apps I see this, I opened: https://github.com/seedvault-app/seedvault/issues/755

**Comment by bettyvschmartz** [comment]
> But what would be the correct wording?

"Ready for backup" perhaps, or even no status message if possible because nothing has happened before backup occurs. There's nothing to report. It should be obvious that apps are ready for a backup to be run. 

-- bvs
