### ISSUE TITLE
Some Files Conflict Nextcloud

### ISSUE THREAD

**Issue by negativzeroe** [seedvault-app/seedvault#235]
Noticing some conflicts of the uploaded files being the same name as the existing files. I've resolved them manually, but since it's not set up via the auto upload feature in the Nextcloud app, I don't have any way to prefer new. Any way that flag could be set via this app?

**Comment by grote** [comment]
I am afraid not. That there's conflicts at all is a Nextcloud bug, because only the app is touching these files.

**Comment by negativzeroe** [comment]
It's not a bug though, it's when it sees a file that has the same properties as a file that exists - it asks if you would rather keep the old version or overwrite with new version. There is an option in the auto-upload within the app under its normal functions that allows you to set a preference for this.

So the issue is when the updated files are backed up but since they are in separate pieces some files are pretty much the same. Now I'm not sure if it really matters all that much or if there is some small change in the encapsulation but I would think there should be a way to call that function during the upload process and flag the backup directory as "prefer new" - yes?

**Comment by grote** [comment]
> It's not a bug though, it's when it sees a file that has the same properties as a file that exists - it asks if you would rather keep the old version or overwrite with new version. 

If that's the case why don't you see hundreds of conflicts for each backup run?

If *only* the Nextcloud app is touching these files, it should keep proper track of their current version. When you overwrite a file and you have its current version, there should *not* be a conflict. A conflict is expected when a file was modified on the server and you try to upload a different modification. In our case, files are never modified on the server, so there should not be conflicts.

> I would think there should be a way to call that function during the upload process and flag the backup directory as "prefer new" - yes?

Seedvault doesn't even know it is talking to Nextcloud, it is using Android's SAF to write files out. So you can't hand any information over to Nextcloud.

**Comment by BenBipod** [comment]
Could it be that SeedVault, while backing up the NextCloud app, triggers some kind of infinite recursion as it holds a local copy of the backup files?

**Comment by grote** [comment]
One can try to use the DavX5 app to backup to Nextcloud.
