### ISSUE TITLE
Build and run instractions / Stand alone application / APK

### ISSUE THREAD

**Issue by cruftex** [seedvault-app/seedvault#243]
Experienced Java developer here, but no Android developer. I am interested to do some improvements to the application.
However, I cannot find any information how to build and run the application.

The only thing I found is:
https://github.com/seedvault-app/seedvault/wiki/Building-with-AOSP

My take away at the moment: 
I would have expected a command that builds an APK
I have what I can or should do with the AOSP build, how would I use the changed backup application in my phone then?
Doing the AOSP build seems to be very complicated (10 stept) and and beyond my time budget

**Comment by grote** [comment]
You can build this like any other Android app using the gradle build system as well. But to really try it your need an AOSP image where you can update a system app. CalyxOS might provide emulator images eventually for this.

**Comment by cruftex** [comment]
What means "system app" and why it is needed? The readme says: 

> `android.permission.BACKUP` to back up application data.

So I thought any application with that permission can do backups.
(Sorry for the naive questions, however, I try hard to find anything with google and working through the Android developer docs, but always get lost)

**Comment by cruftex** [comment]
Meanwhile I found some pointers about "system app" that I can dig into.
However, the questions remains why a backup applications needs to be a system app, while there is a app permission for doing backups.

**Comment by grote** [comment]
> there is a app permission for doing backups.

is there?

I always thought this is a restricted permission that only system apps can have.

**Comment by cruftex** [comment]
> I always thought this is a restricted permission that only system apps can have.

I don't know. I am asking naive why questions, because I think the things are extra complicated. Maybe this is not the right place for it. Where would it be?

Why is backup a system app then? Maybe its because of "added security", so users cannot "accidentally" install an app which has the backup permission. Maybe its because vendors like to ship backup with the system to lock-in users to their ecosystem? On my desktop I am in full control and can do everything.

Its open source, what about looking at the whole thing and try to improve at the right places?

Besides, I see a lot issues with "support XY protocol or storage provider". So here is the idea:

Have a very simple system app which handles the encryption key and provides an interface to access the 
encrypted data with timestamps. Do the backup (upload, download, compression, background run, scheduling) in a normal application. It does not make sense to bloat the system image with support for all the different backup destinations, anyway.

**Comment by chirayudesai** [comment]
> > I always thought this is a restricted permission that only system apps can have.
> 
> I don't know. I am asking naive why questions, because I think the things are extra complicated. Maybe this is not the right place for it. Where would it be?

The BACKUP permission (amongst some more) is something only privileged system apps can have. This is done for security reasons.
> 
> Why is backup a system app then? Maybe its because of "added security", so users cannot "accidentally" install an app which has the backup permission. Maybe its because vendors like to ship backup with the system to lock-in users to their ecosystem? On my desktop I am in full control and can do everything.
> 
It is because of security, because it gives you access to all app data.

> Its open source, what about looking at the whole thing and try to improve at the right places?
> 
> Besides, I see a lot issues with "support XY protocol or storage provider". So here is the idea:
> 
> Have a very simple system app which handles the encryption key and provides an interface to access the
> encrypted data with timestamps. Do the backup (upload, download, compression, background run, scheduling) in a normal application. It does not make sense to bloat the system image with support for all the different backup destinations, anyway.

That is basically all the app does. The upload/download is handled by normal applications, such as Nextcloud. We feed encrypted data to nextcloud which in turn uploads it.
