### ISSUE TITLE
Calllog backup stuck in a loop?

### ISSUE THREAD

**Issue by returntrip** [seedvault-app/seedvault#244]
I have not been able to complete a full backup and most of the time I find nextcloud uploading the calllog over and over again (although under a different file name).

![Screenshot_20210425-070221_Nextcloud.png](https://user-images.githubusercontent.com/14056122/115981625-5fbf1300-a595-11eb-8a35-3fd83f01aba8.png)

While the files are uploading, the backup progress is stuck at 22% and after a while it will fail.

Backup status for all apps, call logs, messages, etc are showing: "Waiting to back up".

Is this a bug with Seedvault or Nexcloud?

LOS 18.1
Oneplus 5T

**Comment by chirayudesai** [comment]
Do you have a lot of call logs?

The current call log implementation doesn't work too well with Nextcloud, however we do have an alternative implementation coming soon.

Till then you can try to disable call log backup once to see if it you can backup everything else without that.

**Comment by returntrip** [comment]
Yeah about 2y worth of them. I did disable the call log backup and I finally manage to create a successfully backup.

Some apps were not backed up (I.e.: Nextcloud and Home Assistant among others).

What backend works best with seedvault in your experience? Thanks.
