### ISSUE TITLE
Consider preventing screenshots on the 12 word display page

### ISSUE THREAD

**Issue by chirayudesai** [seedvault-app/seedvault#246]

**Comment by 2019-05-10** [comment]
Certainly not!
That 12 word puzzle is already of the kind of security, that is so cumbersome, one rather avoids it completely where possible.
Disabling screenshots would make it completely unusable.

**Comment by simonsan** [comment]
> Certainly not! That 12 word puzzle is already of the kind of security, that is so cumbersome, one rather avoids it completely where possible. Disabling screenshots would make it completely unusable.

Can you elaborate please, where it is "cumbersome", why it should be avoided and why screenshots would make it **unusable**?

**Comment by gdt** [comment]
I don't think taking screenshots of the 12 words is a good idea.  But, backup security is a difficult balance between:
 * being able to get your bits back
 * keeping other people from getting at your b its

and I think users should be able to make that choice, and that Free Software should respect the right of users to make choices.   Disabling screenshots is kind of a security by obscurity mechanism, as it's trivial to take a  picture with another camera.  However with squeeze-to-screenshot, I can see the point of avoiding it by accident.

**Comment by grote** [comment]
> Disabling screenshots is kind of a security by obscurity mechanism, as it's trivial to take a picture with another camera.

That's not the idea. The idea is that you don't have a screenshot of your backup secret on the same phone where it can be accessed by many other apps some potentially being malware specialized in BIP39 secrets to steal cryptocurrency.

This has been implemented already, so closing.

**Comment by 2019-05-10** [comment]
Well,  good thing I got rid of Seedvault then.
This "don't care, don't listen, f*** off" attitude is certainly helping to spread the word.

**Comment by chirayudesai** [comment]
> Well, good thing I got rid of Seedvault then. This "don't care, don't listen, f*** off" attitude is certainly helping to spread the word.

This kind of talk is not welcome here.

Don't forget this is a free and open source project, and it's not like we don't listen - there's so many things to do, and with such things there will always be some people unhappy.

Allow screenshots - the security conscious people may not like that.

Don't - well, here we go.

There's just no winning sometimes, but I kindly ask to refrain from this kind of language here, and have a civil and productive discussion. Thank you.
