### ISSUE TITLE
Both backup error and backup running notifications

### ISSUE THREAD

**Issue by whatapleasantsurprise** [seedvault-app/seedvault#252]
When plugging in my flash drive I always get a backup failed notifications and, after a few seconds, a backup running one. The backup running notifications doesn't have a percentage and just shows a progress bar but the backup does nevertheless complete ([screenshot](https://user-images.githubusercontent.com/84041842/117871800-5ae4a980-b28d-11eb-9b09-bdadfaacdab8.png) for visual aid). Here is the [logcat](https://github.com/seedvault-app/seedvault/files/6461474/logcat.txt).

**Comment by grote** [comment]
Thanks for the report and logcat!

Is this for the main user or another user account? This happens everytime you insert the flash drive? This is the same flash drive that you chose as a storage location in Seedvault?

relevant log extracts:

```
java.lang.IllegalStateException: android.content.pm.PackageManager$NameNotFoundException: Application package com.android.settings not found
...
05-11 21:50:46.760  4110  5870 I NotificationBackupObserver: Showing progress notification for org.calyxos.backgrounds 147/164
05-11 21:50:46.773  4110  5870 W Binder  : Caught a RuntimeException from the binder stub implementation.
05-11 21:50:46.773  4110  5870 W Binder  : java.lang.IllegalStateException: expectedApps is null
05-11 21:50:46.773  4110  5870 W Binder  : 	at com.stevesoltys.seedvault.ui.notification.BackupNotificationManager.onBackupUpdate(BackupNotificationManager.kt:128)
05-11 21:50:46.773  4110  5870 W Binder  : 	at com.stevesoltys.seedvault.ui.notification.NotificationBackupObserver.showProgressNotification(NotificationBackupObserver.kt:95)
05-11 21:50:46.773  4110  5870 W Binder  : 	at com.stevesoltys.seedvault.ui.notification.NotificationBackupObserver.onUpdate(NotificationBackupObserver.kt:47)
05-11 21:50:46.773  4110  5870 W Binder  : 	at android.app.backup.IBackupObserver$Stub.onTransact(IBackupObserver.java:132)
05-11 21:50:46.773  4110  5870 W Binder  : 	at android.os.Binder.execTransactInternal(Binder.java:1159)
05-11 21:50:46.773  4110  5870 W Binder  : 	at android.os.Binder.execTransact(Binder.java:1123)
```

The first appearance of  `BackupManagerService` is at 21:48:45.461 where it already backs up packages. Logs from when the flash drive was inserted and the initial error happened seem to be missing.

**Comment by whatapleasantsurprise** [comment]
It is the main user, it happens every time and with the same flash drive that I've used since day one.

**Comment by grote** [comment]
Thanks. Could you then please provoke the error again and record the logcat from the exact moment when you insert the flashdrive?

**Comment by whatapleasantsurprise** [comment]
Do I leave the backup to finish or do I need to force stop seedvault?

**Comment by whatapleasantsurprise** [comment]
Also, does forwarding the system clock trigger a background backup?

**Comment by grote** [comment]
> Do I leave the backup to finish or do I need to force stop seedvault?

Best to do it when there's no current activity and the drive had been removed for some time.

> Also, does forwarding the system clock trigger a background backup?

USB backups don't do background backups as drives are usually not plugged in all the time. The backup gets triggered when the drive gets inserted after more than 24h after the last backup. Messing with the system clock isn't supported and wasn't tested.

**Comment by whatapleasantsurprise** [comment]
> > Do I leave the backup to finish or do I need to force stop seedvault?
> 
> Best to do it when there's no current activity and the drive had been removed for some time.

This is what I have done last time, wait for the backup to finish, eject the flash drive and get a logcat, I will try again today though.
Should I have the flash drive already inserted before 21:50 or do I plug it in after that?
> > Also, does forwarding the system clock trigger a background backup?
> 
> USB backups don't do background backups as drives are usually not plugged in all the time. The backup gets triggered when the drive gets inserted after more than 24h after the last backup. Messing with the system clock isn't supported and wasn't tested.

This is a bit of a shame as my only problem is when the backup start automatically and, trying to test things out with 1 day between each attempt makes it very difficult to gather any data.

**Comment by grote** [comment]
> This is what I have done last time, wait for the backup to finish, eject the flash drive and get a logcat

The space for logcat is limited. This explains why the beginning was missing.

Please get the logcat short after inserting the flash drive and the error happening together with the backup starting. Once the backup has started, the rest of the logacat is most likely not interesting anymore.

If you rely on USB for getting the logcat, you can set up adb over TCP/IP first, e.g. by running `adb tcpip 5555` first and then connecting to the device via `adb connect [ip]`.

**Comment by whatapleasantsurprise** [comment]
The new [logcat](https://github.com/seedvault-app/seedvault/files/6468541/logcat.txt), taken a few seconds after the backup running notification popped up.

**Comment by grote** [comment]
Was there also an error notification this time? Does it appear before or after the backup running notification?

I don't really find a problem in that log.

**Comment by whatapleasantsurprise** [comment]
The error notification always appears first. It was the exact same as every other time:
- I plug in the flash drive
- (after ~5 sec) I get an error notification
- (after ~7 sec) I get a backup running notification

**Comment by grote** [comment]
I went through the log again and there's nothing logged for why an error notification is shown. It is also not clear if the backup was initiated by the Usb drive getting mounted or not. There's log entries missing for some reason. Here are some potentially relevant log entries in case we need to analyze later:
```
05-12 21:38:54.113  1581  1972 I BackupManagerService: Backup not activated for user 10
05-12 21:38:54.115  1581  1815 W ActivityManager: UserLifecycleEvent 6 received without an active userJourneySession.
05-12 21:38:54.115  1581  1815 I ActivityManager: User 10 state changed from RUNNING_UNLOCKING to RUNNING_UNLOCKED
05-12 21:38:54.115   610   623 I vold    : Bind mounting /mnt/runtime/full/emulated to /mnt/pass_through/10/emulated
05-12 21:38:54.117  1581  1938 I StorageSessionController: On volume mount VolumeInfo{emulated;10}:
05-12 21:38:54.117  1581  1938 I StorageSessionController:     type=EMULATED diskId=null partGuid= mountFlags=PRIMARY|VISIBLE 
05-12 21:38:54.117  1581  1938 I StorageSessionController:     mountUserId=10 state=CHECKING 
05-12 21:38:54.117  1581  1938 I StorageSessionController:     fsType=null fsUuid=null fsLabel=null 
05-12 21:38:54.117  1581  1938 I StorageSessionController:     path=/storage/emulated internalPath=/data/media 
05-12 21:38:54.231  1581  1815 I ActivityManager: Posting BOOT_COMPLETED user #10 
...
05-12 21:38:55.666  1581  1581 I TransportClient: ConfigurableBackupTransportService#1: Notifying [TransportManager.registerTransport()] transport = IBackupTransport
05-12 21:38:55.689  1581  3198 D BackupTransportManager: Transport com.stevesoltys.seedvault/.transport.ConfigurableBackupTransportService registered
05-12 21:38:55.689  1581  3198 D BackupManagerService: [UserID:0] Transport com.stevesoltys.seedvault.transport.ConfigurableBackupTransport registered 3455ms after first request (delay = 3000ms)
05-12 21:38:55.704  1581  3198 I BackupManagerService: [UserID:0] Found stale backup journal, scheduling
05-12 21:38:55.704  1581  3198 I chatty  : uid=1000(system) backup-0 identical 12 lines
...
05-12 21:56:49.941  1581  1938 I StorageManagerService: Mounted volume VolumeInfo{public:8,1}:
05-12 21:56:49.941  1581  1938 I StorageManagerService:     type=PUBLIC diskId=disk:8,0 partGuid= mountFlags=0 mountUserId=0 
05-12 21:56:49.941  1581  1938 I StorageManagerService:     state=MOUNTED 
...
05-12 21:56:59.926  2412  2412 E Settings: Failed to create user context
05-12 21:56:59.926  2412  2412 E Settings: android.content.pm.PackageManager$NameNotFoundException: Application package com.android.settings not found
...
05-12 21:56:59.962  2412  2412 W LayerDrawable: Invalid drawable added to LayerDrawable! Drawable already belongs to another owner but does not expose a constant state.
05-12 21:56:59.962  2412  2412 W LayerDrawable: java.lang.RuntimeException
...
05-12 21:57:00.453  5493  5493 D ConfigurableBackupTransportService: Service destroyed.
05-12 21:57:00.459  5493  5552 I ConfigurableBackupTransportService: Backup succeeded 
05-12 21:57:00.459  1581  3198 V BackupManagerService: [UserID:0] Acquired wakelock:*backup*-0-3198
05-12 21:57:00.460  1581  3198 D KeyValueBackupTask: Spinning thread key-value-backup-1
05-12 21:57:00.461  1581  5571 D PFTBT   : backupmanager pftbt token=55497502
05-12 21:57:00.469  5493  5553 I BackupNotificationManager: 0/164 - 0% - 
05-12 21:57:00.472  1581  5571 V KeyValueBackupTask: Beginning backup of 11 targets
05-12 21:57:00.475  5493  5493 D ConfigurableBackupTransportService: Service created.
05-12 21:57:00.475  5493  5493 D ConfigurableBackupTransportService: Transport bound.
05-12 21:57:00.476  1581  1581 I TransportClient: ConfigurableBackupTransportService#4: Notifying [KVBT.startTask()] transport = IBackupTransport
05-12 21:57:00.478  1581  5571 D KeyValueBackupTask: Starting key-value backup of @pm@
```

**Comment by grote** [comment]
@whatapleasantsurprise do you still experience this issue? Is it possible that one notification was for a different user profile and inserting the drive started a backup for two profiles at once?
