### ISSUE TITLE
Backup/restore doesn't actually do anything

### ISSUE THREAD

**Issue by alfiedotwtf** [seedvault-app/seedvault#255]
From a fresh LineageOS install, to simulate regular usage I've installed firefox, moved an icon to a different position on the home screen, and took a photo. I then proceeded to backup using the built-in Seed Vault to a connected USB stick. The backup ran successfully and shows a 66Mb file on the stick.

After doing a factory reset, when the installer says to restore using the saved seed words, it successfully reads the files off the disk and writes. However, on reboot, it's almost like we're back to a factory reset - firefox isn't installed, the firefox APK isn't in the download folder, there are no photos in the gallery app, and the moved icon on the home screen is back to it's default position.

**Comment by grote** [comment]
> it successfully reads the files off the disk and writes

Would be nice to receive screen photos or a video of that process to see what is happening. A logcat might also assist with debugging. I think Firefox doesn't allow backups, but the APK should get backed up and re-installed.

**Comment by Rihcus** [comment]
I have a similar issue with lineage OS 18.1. After enabling backups it is stuck on waiting to backup
![Screenshot_20210517-133833_Seedvault](https://user-images.githubusercontent.com/30292597/118532674-39fcd800-b715-11eb-95ec-bf1dfe9933be.png)

**Comment by grote** [comment]
@Rihcus that does not seem to be the same issue at all. In your case, the system simply hasn't run a backup, yet. Try using the `Backup now` option from the overflow menu.

**Comment by Rihcus** [comment]
> @Rihcus that does not seem to be the same issue at all. In your case, the system simply hasn't run a backup, yet. Try using the `Backup now` option from the overflow menu.

Thanks for the reply that seems to do the trick :)

**Comment by alfiedotwtf** [comment]
Ok, I went through the backup and restore in order to capture any errors, but it looks like it worked :)
