### ISSUE TITLE
Recovery seed words cut off

### ISSUE THREAD

**Issue by thelifeofjay** [seedvault-app/seedvault#256]
It seems the recovery words page isn't responsive to the size
of the device font. Tested and reproduced on CopperheadOS Pixel 3a (Sargo)
on Seedvault version 11-1.1

![screenshot_seedvault](https://user-images.githubusercontent.com/4836456/118561122-932a3300-b738-11eb-92d7-9875477556a9.jpg)

Fixed by using a smaller device font but not useful for devices that have accessibility requirements.

**Comment by grote** [comment]
Closed by #276
