### ISSUE TITLE
Documentation about the backup format.

### ISSUE THREAD

**Issue by jtagcat** [seedvault-app/seedvault#260]
Yesterday the Spotify app got an update, what immediately crashed on launch, even without user data. Thus I went looking for an APK to downgrade to.

This is confusing:

![image](https://user-images.githubusercontent.com/38327267/120069832-76b2c280-c077-11eb-9f75-9fb8973d6643.png)

How should I know which of them is correct. Are they partial APKs, are they deltas, are they full revisions? I would make that they are 3 or 4-part APKs, and snapshots.

What's the intended process to restore only an app (without touching the data, as else, it'd need to download 50G)?

**Comment by grote** [comment]
Spotify is using app bundles which consist of most of all those APKs there. Restoring a single app is currently not supported. You can let auto-restore activated. Uninstall the app and then reinstall an old version manually.
