### ISSUE TITLE
no useful information about backup to be created

### ISSUE THREAD

**Issue by 2019-05-10** [seedvault-app/seedvault#263]
There's no information where this backup will be created nor how large it will be.
This makes it rather hard to use -- with my Nextcloud account I need to know how much space the backup will take up (and how long transfer would take).
For a USB stick as well.
So, the only sensible option is local backup -- still with the risk of either running out of space or/and the backup crashing.
To get it to my local computer I need to know where the backup is created.
To purge it, as well since there's apparently no way either to clean up backups.

**Comment by rugk** [comment]
Well… okay, I'd propose to add something like this [in the FAQ](https://github.com/seedvault-app/seedvault/wiki/FAQ) (unfortunately not publicly editable):
> ## Where is my backup saved?
> It is saved in the `.SeedVaultAndroidBackup` directory in your choosen backup location. On non-Windows systems this is a hidden folder due to the `.`. And as syncing hidden files is disabled in the Nextcloud desktop clients by default, the backup data does not end up on your connected desktop clients.
> If you have the synchronization of hidden files enabled, it is recommend to put `.SeedVaultAndroidBackup` on your exclude list.

**Comment by grote** [comment]
added

**Comment by rugk** [comment]
Ya thanks! As such, can we close this issue @2019-05-10 or is there anything else?

**Comment by julianfoad** [comment]
I found the information in the FAQ when I went looking. I'm a power user and that was enough to get the job done for me, but I think finding it in the FAQ is a second-rate "solution". For any regular user it is really not good enough.

Please add some sort of discoverability in the interface. Could include a statement that says where it is (copy the FAQ to a pop-up text in the app, at a minimum), and probably also a button to open the backup location (in a local file manager for local paths, or Nextcloud app when Nextcloud selected).
