### ISSUE TITLE
Feature Request: Add owncloud as backup location option

### ISSUE THREAD

**Issue by m-rey** [seedvault-app/seedvault#265]
It would be great to also support backing up to an owncloud instance. I've noticed that there's already support for nextcloud (nice!). Iirc both nextcloud and owncloud have many similarities, so I hope that it's also possible/feasible to implement the functionality for owncloud.

 
I've read through other related issues to get a rough idea of what would be necessary for that:  

* The owncloud app is open source (GPL 2 only) and available on the main fdroid repository: https://f-droid.org/packages/com.owncloud.android

* Regarding the SAF requirement: While I'm not 100% sure, I really think the app uses the SAF.  I'll take a closer look soon.

What do you think?

**Comment by chirayudesai** [comment]
They do support SAF, but may not support the exact APIs we want.

https://github.com/seedvault-app/seedvault/issues/169 has some more details.

You can try enabling it by adding it to https://github.com/seedvault-app/seedvault/blob/0e3147b365e78e51a48621a3db9ee28f811a4375/app/src/main/res/values/config.xml#L17
