### ISSUE TITLE
opening "Sicherungsort (backup location)" and selecting the existing option resets backup state

### ISSUE THREAD

**Issue by eighthave** [seedvault-app/seedvault#267]
In CalyxOS, I went to Settings -> System -> Advanced -> Backups.  The option Sicherungsort (backup location) had "Nextcloud" written under it in the summary text field.  I clicked on that option and it brought me to the screen to choose where the backups go (Wählen SIe aus, wo die Sicherungen gespeichert werden sollen).  The options were my local device, Nextcloud, and a greyed out "USB-Speichergerät (USB storage)".  I clicked on Nextcloud, and it brought me back to the backup settings (Sicherung).  "Backup status" now said "Letzte Sicherung: nie (last backup: never)". 

If I choose the already configured option, I think nothing should change.  Otherwise, that settings screen becomes extra scary since its easy to mistakenly reset things.  The screen to choose where the backups go (Wählen SIe aus, wo die Sicherungen gespeichert werden sollen) does not have a back button, so it seems the only way out is to click on one of the options.

I think two things should happen to fix this:
* add the standard back button on the upper left like the other settings screens have
* choosing the existing option should have the same effect as clicking back, e.g. nothing changes.
* Bonus: add an indicator for which option is currently active.

**Comment by grote** [comment]
> "Backup status" now said "Letzte Sicherung: nie (last backup: never)".

Below the headline, there's a warning icon saying "Existing backups in this location will be deleted."

> add the standard back button on the upper left like the other settings screens have

I agree. It seems it is using the view-mode from setup wizard where this is hidden.

> choosing the existing option should have the same effect as clicking back, e.g. nothing changes.

Not sure about this one. If we indicate the currently active option, we should maybe not even make it selectable again. However, then we need another UI option somewhere to start a new restore set for app backups.

**Comment by eighthave** [comment]
Torsten Grote:
>> "Backup status" now said "Letzte Sicherung: nie (last backup: never)".
> 
> Below the headline, there's a warning icon saying "Existing backups in this location will be deleted."

Is there something you want me to do there?

>> choosing the existing option should have the same effect as clicking back, e.g. nothing changes.
> 
> Not sure about this one. If we indicate the currently active option, we should maybe not even make it selectable again. However, then we need another UI option somewhere to start a new restore set for app backups.

I'm sure Android has existing guidelines on what pattern to use here.  My guess 
is that the pattern is that all options remain clickable.  I don't know about 
the restore set, so I can't respond to that.

**Comment by grote** [comment]
When https://github.com/seedvault-app/seedvault/pull/750 is merged choosing the existing location again will have no effect.
