### ISSUE TITLE
App only backuped 15% of apps (15 out of 93), no way to select the remainder

### ISSUE THREAD

**Issue by ioogithub** [seedvault-app/seedvault#268]
I want to have a full backup of all apps on my system. Most of the apps have a caution icon next to them and I can't see anyway to get them backed up.

Please include a simple "Select All" check mark to allow users to take a backup of all apps. A backup solution that only backs up 15% of the apps and does not allow the user to backup the remaining 85% is not at very useful.

**Comment by grote** [comment]
We would need to find out for each app, why there's errors backing it up. See https://github.com/seedvault-app/seedvault/issues/147 for an example where that has been done.

We'd also need the version of seedvault that you are using and ideally a logcat of the backup process.

**Comment by julianfoad** [comment]
Duplicate issue, but with more info and discussion: #684 "Backup does not work for most apps"
