### ISSUE TITLE
Seedvault is unintentionally implicitly GPLv3 due to NovaCrypto/BIP39 library

### ISSUE THREAD

**Issue by grote** [seedvault-app/seedvault#272]
https://github.com/NovaCrypto/BIP39/blob/master/LICENCE.txt

We can ask its author to also license under Apache2 or move to a different library.

Since this is a security critical library, it was also suggested to implement the few bits we need ourselves to prevent upstream from making a malicious change that allows them to decrypt people's backups.

**Comment by chirayudesai** [comment]
Alternative solution: Switch to https://github.com/zcash/kotlin-bip39 - perhaps vendor it in, it doesn't have any dependencies apart from kotlin stdlib.

However, it uses [kotlin 1.4.30](https://github.com/zcash/kotlin-bip39/blob/master/buildSrc/src/main/java/cash/z/ecc/android/Dependencies.kt#L6) so we won't be able to build it with AOSP 11.

We could still have the source in here and have a lib for AOSP usage, like the storage library.

**Comment by chirayudesai** [comment]
Another implementation I found https://github.com/mycelium-com/wallet-android/blob/master/bitlib/src/main/java/com/mrd/bitlib/crypto/Bip39.java

**Comment by eighthave** [comment]
If you use the gradle verification that was added in v6.4, then you can trust that your builds are getting the same library binary each time.  Then if you're able to reproducibly build the library to confirm it, there is no need to vendor it.  Just inspect the changes when you update it.

**Comment by chirayudesai** [comment]
> If you use the gradle verification that was added in v6.4, then you can trust that your builds are getting the same library binary each time. Then if you're able to reproducibly build the library to confirm it, there is no need to vendor it. Just inspect the changes when you update it.

We still need to vendor it anyway for AOSP build.
