### ISSUE TITLE
[Feature Request] Backup intervals or location restricted backup

### ISSUE THREAD

**Issue by asuh** [seedvault-app/seedvault#284]
I am using a local Nextcloud for my backup. In Nextcloud app, I've got it set up with a local IP address. When I leave my LAN, I regularly get notifications from failed backups. It makes sense that they're failing since the IP address of Nextcloud is a non-routable IP inside my LAN.

The feature I would like to request is one of two features:
- interval selection, such as every 24 hours so that it can backup only during the night
- location based restriction. As long as my IP is coming from the LAN, in a certain IP range, it can back up.

Either or both of these features would be great.

**Comment by grote** [comment]
This is unlikely to get implemented in Seedvault. IMHO Nextcloud should handle this and only attempt uploads when its server is reachable. It is caching backup data locally anyway, so it could just upload once the server is available.
