### ISSUE TITLE
Cannot restore the backup(No suitable backup found at given location)

### ISSUE THREAD

**Issue by beinganukul** [seedvault-app/seedvault#285]
![](https://f000.backblazeb2.com/file/screenshots-bucket/Screenshot_20210713-024554_Seedvault.png)
I backed up from previous lineage os install.
wiped system
installed lineage os
and this shows. 
Any way to recover previous data

**Comment by chirayudesai** [comment]
Did you backup to "internal storage"?

If you wiped data that will be gone sadly.

**Comment by beinganukul** [comment]
> Did you backup to "internal storage"?
> 
> If you wiped data that will be gone sadly.

i did wipe internal storage
but all files are there in hidden folder of seedvault
