### ISSUE TITLE
Update Changelog for `11-2.1`

### ISSUE THREAD

**Issue by grote** [seedvault-app/seedvault#292]
Update [`CHANGELOG.md`](https://github.com/seedvault-app/seedvault/blob/96ffcc258d1ec0242483052f60067fa69f21ef7e/CHANGELOG.md) for last release.

Maybe we should have a release checklist to not forget about these things...

**Comment by chirayudesai** [comment]
I didn't forget, I wrote it in the tag, see:

https://github.com/seedvault-app/seedvault/releases/tag/11-1.2
https://github.com/seedvault-app/seedvault/releases/tag/11-1.1

It's just that we never did a CHANGELOG for 11-1.0 and it was a big update, I didn't have time to write it then.

**Comment by chirayudesai** [comment]
It'd be good to have a release checklist.

We can also have platform signed APKs available (can have the CI provide them) to help.

**Comment by chirayudesai** [comment]
Will be done by https://github.com/seedvault-app/seedvault/pull/320
