### ISSUE TITLE
Prebuilt APK says "Unable to install app" and nothing else, no further info, when trying to install it

### ISSUE THREAD

**Issue by IveMalfunctioned** [seedvault-app/seedvault#294]

**Comment by Glutamat42** [comment]
"no further info" just like your report. I just can guess the reason might be "This application is compiled with the operating system". I dont think it is possible to install it like other apps on your already running system.

**Comment by IveMalfunctioned** [comment]
Fuck off if you're gonna be rude for no reason. There was literally no way for me to get further info.
