### ISSUE TITLE
Device Settings Not Restored Part 2; Request for Expert-Level Control

### ISSUE THREAD

**Issue by vindicatorr** [seedvault-app/seedvault#296]
Continuing on where I left off with https://github.com/seedvault-app/seedvault/issues/295
After figuring out how to restore "Device settings" (aka com.android.settings), and successfully doing it with "com.android.localtransport/.LocalTransport", I now went and ran backup normally in Settings->Backup, where I excluded everything except for "Device settings"

To restore:
```
$ adb bmgr --user 0 list sets
$ adb bmgr --user 0 restore <set#> com.android.settings
Scheduling restore: <my device>
restoreStarting: 1 packages
onUpdate: 0 = com.android.settings
restoreFinished: 0
```
Yet the restore failed to work as I had made a clear visual change (dark-mode) after the backup, and it didn't revert back.

But if I backup/restore with com.android.localtransport/.LocalTransport, it does work.

EDIT0: Copying the backup data to a secondary user and restoring for that user doesn't work as expected/desired. There's EPERM and EACCES errors since the adb user id is not that of the secondary user.
Using a terminal emulator app for a secondary user also didn't work as it didn't request "android.permission.BACKUP" which I found out is only used for "system apps" (eg. seedvault I'm guessing).
I also saw that from Pie(9)+, manual restore is removed in the backupmanager api.

So maybe this is more going to be a request to have an "advanced/expert" section where bmgr commands can be executed manually.

**Comment by grote** [comment]
Are you sure `com.android.settings` is the right package name? Using secondary users for restoring system settings might also be broken in AOSP.

I am only not closing this, because you say that it works with `com.android.localtransport/.LocalTransport`. A logcat from using seedvault and localtransport would be helpful.
