### ISSUE TITLE
LineageOS 11 and backup in Nextcloud

### ISSUE THREAD

**Issue by ankx7** [seedvault-app/seedvault#298]
HI! i've a problem with backup in my Nextcloud account:
if i put backup in local storage it's ok but in Nextcloud....the backup stops approximately 50%.
can i debug or there is a log file to send you?

**Comment by rugk** [comment]
`logcat` is always a good thing for debugging…

**Comment by ahanniga** [comment]
I'm having the same problem. Installed Logcat Reader, but it contains no logs related to Seedvault.

**Comment by rugk** [comment]
It can also be related to Nextcloud, if it uploads it.

Also please provide version numbers of Nextcloud, Seedvault and your CustomROM (and you likely won't use LineageOS 11, because that would be years old, it's likely a typo).

**Comment by ahanniga** [comment]
Backing up on USB works fine, it's just the Nextcloud connection that fails. Version numbers are:

- Nextcloud Android App version 3.16.1 
- on Pixel 5, CalyxOS 2.8.0 (Android 11)
- Seedvault (pre-installed) version 11-2.1

**Comment by grote** [comment]
I suggest to try the DavX5 app for the nextcloud connection instead. We can't do anything about the nextcloud app/connection.
