### ISSUE TITLE
Allow setting the path for backups

### ISSUE THREAD

**Issue by imsodin** [seedvault-app/seedvault#300]
I do my backups on the external SD card (which is also synced with Syncthing) - so far so good. Now I had a case where my phone was unusable so I took that as an opportunity to test phone backup restore. I moved the SD card to another phone and restored - worked really well for a lot of apps, obviously not all of them. Now I want to setup backups on that secondary device too. And there's the problem: It will write backups to the same directory as the previous device did. To keep the backups separate, I need to remember moving the .SeedVaultAndroidBackup to another place whenever I move the SD card around. Being able to choose the path where to restore backups from and/or where to backup to would fix that.

**Comment by grote** [comment]
duplicate of #143?

**Comment by imsodin** [comment]
Probably, if that isn't nextcloud specific.
