### ISSUE TITLE
Change branching scheme, again.

### ISSUE THREAD

**Issue by chirayudesai** [seedvault-app/seedvault#301]
Hopefully for the last time.

Current:
* master: development
* android11: stable, translations
* android10, android9: old version-specific branches
* tags: stable

Proposed:
* android12: development, translations
* android11, android10, android9: old version-specific branches
* tags: stable

I am proposing to do away with the `master` branch, and directly develop on `android12`

We've started tagging releases so anybody who wants something stable can use those, and others can keep using the branch.

It'll avoid confusion and also make handling translations easier.

**Comment by grote** [comment]
Fine with me, just not sure what you mean by oldstable tags

**Comment by chirayudesai** [comment]
> Fine with me, just not sure what you mean by oldstable tags

Nothing in particular really, just that they used to be previous stable branches I guess?

Debian just released a "new stable" so that's leaking a bit :P

**Comment by grote** [comment]
> Nothing in particular really, just that they used to be previous stable branches I guess?

ok, because I think the version number of the tag should already make clear what android version it is for and every tag is stable, so I think we don't need to introduce stable/oldstable terminology

**Comment by chirayudesai** [comment]
Steps:
* [x] Merge all pending PRs
* [x] Merge master to android11 - https://github.com/seedvault-app/seedvault/pull/321
* [x] Tag android11 - https://github.com/seedvault-app/seedvault/releases/tag/11-2.2
* [x] Deprecate master - https://github.com/seedvault-app/seedvault/pull/322 
* [x] Push android11 to android12, set that as default.
* [x] Change weblate branch to android12
* [x] Update android12 README, versioning - https://github.com/seedvault-app/seedvault/pull/323

**Comment by grote** [comment]
@chirayudesai  Is that list above up to date? Or can we close this ticket?

**Comment by chirayudesai** [comment]
> @chirayudesai Is that list above up to date? Or can we close this ticket?

Yep!
