### ISSUE TITLE
Seedvault prefills second screen for entering passwords

### ISSUE THREAD

**Issue by rugk** [seedvault-app/seedvault#306]
As far as I understood it, this is how it should work when setting up the backup:
* you see a screen with your passwords and write them down
* the next screen forces you to enter these passwords again to verify that you've _really_ written them down/saved them

## This is what happens

However, the second screen is prefilled with the passwords already and thus you can just skip the screen/press "enter" without checking the words again.

## System

v11-1.1
LineageOS for microG 18.1 2021-08-11
Also reproduced on another device with LineageOS for microG 17.1 IIRC.

**Comment by grote** [comment]
This is because Lineage makes userdebug builds, so Seedvault thinks this is a debug build.

**Comment by rugk** [comment]
So… anyone cares to report this to LineageOS then? Because obviously that should not be like that, should it? :thinking: 

The last time I reported an issue at LineageOS I had to use some straneg GitLab, where I could only post during "working hours" or such a thing… :sweat_smile:

**Comment by rugk** [comment]
https://gitlab.com/LineageOS/issues/android/-/issues/3897

**Comment by rugk** [comment]
Also reported in https://github.com/lineageos4microg/docker-lineage-cicd/issues/218

**Comment by rugk** [comment]
LineageOS has fixed it in their "fork", apparently now by checking for "eng" instead of "userdebug" builds: https://github.com/LineageOS/android_packages_apps_Seedvault/commit/ec1120d37d870424b49a87914e7724bf87e7cc5d

Would this change also be a candidate for upstream here?

**Comment by grote** [comment]
I think they would have submitted it upstream if it would work here as well.

**Comment by chirayudesai** [comment]
> LineageOS has fixed it in their "fork", apparently now by checking for "eng" instead of "userdebug" builds: [LineageOS/android_packages_apps_Seedvault@ec1120d](https://github.com/LineageOS/android_packages_apps_Seedvault/commit/ec1120d37d870424b49a87914e7724bf87e7cc5d)
> 
> Would this change also be a candidate for upstream here?

I intentionally submitted it downstream since userdebug / eng means debug builds generally in Android.

LineageOS builds are userdebug but with a bunch of modifications all around the place to treat it closer to user, and so it makes sense to have this change there.

Anyone else needing the same could cherry-pick / maintain it downstream, since we don't see any easy ways to make a conditional change here.
