### ISSUE TITLE
Choose what apps will get restored

### ISSUE THREAD

**Issue by rugk** [seedvault-app/seedvault#309]
* [ ] New restore UI allowing selection of apps to restore before actual restore process starts
* [ ] Enable restore in normal UI, so users can restore (non-system?) apps even after completing their device setup wizard

---

Somewhat related to https://github.com/seedvault-app/seedvault/issues/100

When I restore a backup, maybe I don't want to restore some apps, I used to have before. IIRC this option was not offered but I know some device transfer services/apps like from Samsung e.g. offer this.

The reasons/use cases may be:
* **technical:** I know the app is only compatible with my old device/StockROM/CustomROM and got accidentally backed up (or in the future because I do things like https://github.com/seedvault-app/seedvault/issues/165)
* **aesthetically:** I want to clean up my system and use this time to start with a smaller step of apps.
  IMHO backup restoration is a good point to reconsider ones decisions about how useful an app was/is/how often it had been used and whether you still need it. Just some chore…
  To support that feature, of course it would be awesome if there was "App was last used three days/months/years ago" or so, if the app was not used for a longer time. But that's rather off-topic…
  BTW for the backing up step of the apps I would not consider this relevant as I rather think that a backup should rather include more data than too less. (that said, I know, of course you can actually already exclude apps/things from being restored here in Seedvault)
* **practically:** I may just want to install some apps, because I'm an CustomROM developer/tester or so and always have my same backup and 5 different devices/emulators or so. For that, I just want a specific set of apps to install (without having to do that manually).
  Or I may have any other obscure reason not to restore a full backup.
  
So it could just present a list of all things pre-selected and let me disable some, I don't want to restore…
I quite wonder why this feature has not been proposed yet, at least I did not find anything in the issue tracker.

**Comment by regulator-g** [comment]
Agreed.. Had a backup of LineageOS with gapps, re-flashed OS with no gapps then seedvault went and added all the google apps back

**Comment by rugk** [comment]
> then seedvault went and added all the google apps back

ouzgh ouch, that sounds fun… i mean sorry but lol… so obvious but obviously not a good thing yeah… :upside_down_face:

**Comment by grote** [comment]
When implementing this it is important to take the possibility into account that the activity gets destroyed (because the user navigates away). It needs to recreate its state when getting restored.
