### ISSUE TITLE
Support Mega as backup target

### ISSUE THREAD

**Issue by pshirshov** [seedvault-app/seedvault#311]
Nextcloud is non-trivial to setup and has some nasty bugs which make backups unreliable.

Mega is e2e encrypted, and it has a [FOSS SDK](https://mega.io/sdk) and all their [clients are FOSS](https://mega.io/sourcecode) and available for audit. 

Also at the moment they provide 20Gb for free

I think that Mega target would be a very worthy addition for everyone.

**Comment by learner5** [comment]
would be great have that option available for my researches and save those files there in Mega.nz

**Comment by alexanderadam** [comment]
Can't you use Mega (and basically any other storage provider) by using [RCX](https://github.com/x0b/rcx#rcx---rclone-for-android) or [extRact](https://github.com/newhinton/extRact#extract---rclone-for-android) ([some Android Rclone clients](https://rclone.org/mega/)) by [activating SAF](https://x0b.github.io/docs/#adding-local-storage-saf)? :thinking: 

And I guess this would probably also be a solution for [Google Drive](https://rclone.org/drive/) (#167), [Seafile](https://rclone.org/seafile/) (#169), [pCloud](https://rclone.org/pcloud/) (#229), [SFTP](https://rclone.org/sftp/) (#173), [WebDav](https://rclone.org/webdav/) (#317) and [the general rclone issue](https://github.com/seedvault-app/seedvault/issues/196)?

Maybe a general integration that allows other app maintainers to integrate these would be useful (_see also [this](https://github.com/x0b/rcx/issues/211) and [this](https://github.com/newhinton/extRact/discussions/23)_).

**Comment by grote** [comment]
This can now be used via Roundsync added in #609
