### ISSUE TITLE
Call Log Backup/Restore question

### ISSUE THREAD

**Issue by Diapolo** [seedvault-app/seedvault#318]
I wiped my phone to install LineageOS 18.1 and have a recent LineageOS 17.1 SeedVault backup. I'm now at the setup where SeedVault restores the backup and wonder how long will it take to restore 1000 files from "Call Log Backup/Restore" step? Will this or should this work at all?

Edit: I'm already waiting for more than half an hour and still can scroll in the app, so it's at least not frozen ;-).

Thanks,
Dia

**Comment by grote** [comment]
questions go here please: https://github.com/seedvault-app/seedvault/discussions

it depends on where the files are stored. on fast flash storage it should take a few minutes, but slow network storage can take hours
