### ISSUE TITLE
Backing up the internal storage - /sdcard

### ISSUE THREAD

**Issue by chirayudesai** [seedvault-app/seedvault#57]
We should backup the entirety of the internal storage as well.
While it might be too big for certain cloud providers, it would be just fine if backing up to removable storage.

It also has the added benefit of backing up what we want from #36 , i.e. backing up internal storage would also backup WhatsApp's directory which would include it's chat backup databases and media files as well.

**Comment by chirayudesai** [comment]
Considerations
* Network speed of both the device and cloud provider.
* Free space remaining, for both cloud provider and removable storage. Ideally you'd want as much free space as the internal storage + slightly more to account for any extras.
* Versioning - Do we delete files deleted locally?
* Checksums - What would be the most efficient method for files large and small, and also sometimes high in number.

**Comment by simonsan** [comment]
> Considerations
> 
>     * Network speed of both the device and cloud provider.
> 
>     * Free space remaining, for both cloud provider and removable storage. Ideally you'd want as much free space as the internal storage + slightly more to account for any extras.
> 
>     * Versioning - Do we delete files deleted locally?
> 
>     * Checksums - What would be the most efficient method for files large and small, and also sometimes high in number.

Use something like `restic` under the hood.
Advantages:
- it's encrypted
- it can upload itself already to different providers like AWS, FTP, Google Cloud Storage
- maybe something to implement a WebDAV for nextcloud backend might be cool also for them
- you can upload small chunks of data over time instead of one big file
- it has versioning of backups included
- restoring and searching inside the backup is easy, also for single files/apps
- it takes care of all that checksums stuff
- it's Linux native
- you could easily initialize one or more backup repository/ies on an external medium or the same device and copy the whole folder (maybe archive it before within seedvault)

https://restic.net/
restic.readthedocs.io/

**Comment by grote** [comment]
@simonsan the design for the backup system is currently drafted here: https://github.com/grote/seedvault-LFB/#overview

Design goals are to re-use the same recovery key and the same storage backends that Seedvault currently supports as well as supporting Android's storage abstractions such as MediaStore.

Feedback is welcome!

**Comment by grote** [comment]
I looked a bit into restic and here's why I'll probably reinvent the wheel:

* it is not yet designed to be used as a library
    * no way to provide our own key material (though we could probably provide the 12 words mnenomic as passphrase, but then can't use the Android keystore and need to retain the passphrase)
* works on file-systems (though there's a bit of an abstraction layer)
    * app data is no file system and hard to map to the abstraction
    * raw file-system access to external storage might go away on Android
* difficulty to build a go library within AOSP (might be able to include as a pre-built)
* doesn't support Android's Storage Access Framework (SAF) currently used by Seedvault as storage backend
* it contains a lot of complexity which is not needed in the Android context

**Comment by simonsan** [comment]
Absolutely valid points, thanks for sharing and taking time to think about/make research on it. 👍

**Comment by khimaros** [comment]
would this design include backing up `/storage/emulated/0/Android/data/`? now that Android 11 has locked down syncthing access to this folder, i'm seeking an alternative and hope SeedVault fits the bill.

**Comment by jtagcat** [comment]
before you reinvent, do take a quick look at https://github.com/restic/others

**Comment by beroal** [comment]
>     * raw file-system access to external storage [might go away](https://cs.android.com/android/platform/superproject/+/android-11.0.0_r3:frameworks/base/core/java/android/os/Environment.java;l=667;drc=android-11.0.0_r3) on Android

There is a new permission `MANAGE_EXTERNAL_STORAGE` in Android 11 specifically for backup applications:

> For example, an anti-virus app's primary use case might require regular scanning of many files across different directories. … Other use cases—such as file manager apps, backup and restore apps, and document management apps—may require similar considerations. …
> When an app has the MANAGE_EXTERNAL_STORAGE permission, it can access these additional files and directories using either the MediaStore API or direct file paths.

Did you look into it? Although it does not grant access to `/Android/data` for some reason.

**Comment by bettyvschmartz** [comment]
I was surprised to see when testing a restore that seedvault doesn't backup internal storage and folders such as Download, Documents and others. 

I can use Syncthing to work around this but I think most users would assume this is backed up. 

-- BVS
