### ISSUE TITLE
Allow regenerating the recovery code

### ISSUE THREAD

**Issue by chirayudesai** [seedvault-app/seedvault#62]
I recently lost the 12 words for a test device, and had to go to Settings to clear app data for Seedvault to reset the code.

It would be good to have an option in the menu for this, with one or more confirmations and warnings as needed.

- [ ] Allow regenrating passphrase
- [ ] Allow deleting old backups, per storage

**Comment by grote** [comment]
Maybe there should also be an option to delete past backups from storage as they are useless now?

**Comment by chirayudesai** [comment]
Yeah, that would be useful too

**Comment by grote** [comment]
I think we should require the storage to be preset and delete old backups after showing a warning before changing the recovery code.

**Comment by chirayudesai** [comment]
I don't think we should. The storage may have been lost, or accidentally formatted, or a number of things.

Warnings sound good, and asking them to plug in if available sounds good too. But it shouldn't be required.

It could go

1. Change passphrase
2. Warning this will make your existing backups useless
3. Plug in $storagelocation to delete old backups (optional / can skip)
4. Delete backups if available
5. Change key
6. (Offer to?) Make fresh backup with new keys.
