### ISSUE TITLE
Seedvault bypasses device policy for installing apps

### ISSUE THREAD

**Issue by thestinger** [seedvault-app/seedvault#78]
There are 3 relevant profile restrictions: [`DISALLOW_INSTALL_APPS`](https://developer.android.com/reference/android/os/UserManager#DISALLOW_INSTALL_APPS), [`DISALLOW_INSTALL_UNKNOWN_SOURCES`](https://developer.android.com/reference/android/os/UserManager#DISALLOW_INSTALL_UNKNOWN_SOURCES) and [`DISALLOW_INSTALL_UNKNOWN_SOURCES_GLOBALLY`](https://developer.android.com/reference/android/os/UserManager#DISALLOW_INSTALL_UNKNOWN_SOURCES_GLOBALLY).

Seedvault currently provides a bypass for these restrictions, by using the privileged permission for installing apps without enforcing these. These are core features for locking down profiles as part of device management, either for an enterprise deployment or by the owner of the device. Any app from the backup needs to be considered as coming from an unknown source, so if any of these user profile restrictions is active for the profile Seedvault should disable installing apps from the backup.

**Comment by chirayudesai** [comment]
We'd also need to account for `DISALLOW_UNINSTALL_APPS` for the auto-restore notification which has an "uninstall" button.

**Comment by grote** [comment]
Is there another install API we could use that already respects these profile restrictions (that doesn't require user-interaction) or there just this one API and it is it simply our responsibility to observe these restrictions when we use it?

Normally, Seedvault restore and app-install capabilities are only meant to be used during setupwizard. Does this change the picture maybe? Are restrictions in effect before the device is provisioned?

> We'd also need to account for DISALLOW_UNINSTALL_APPS for the auto-restore notification which has an "uninstall" button.

This button however makes use of a deprecated API that requires user-interaction for uninstall, so maybe that already observes the restriction?

**Comment by thestinger** [comment]
> Normally, Seedvault restore and app-install capabilities are only meant to be used during setupwizard. Does this change the picture maybe? Are restrictions in effect before the device is provisioned?

I don't think so, since the best way of setting up a device manager is doing it as the first step of provisioning to make sure the restrictions are enforced from that point on. That's how Google's own enterprise device management works.

**Comment by thestinger** [comment]
> Is there another install API we could use that already respects these profile restrictions (that doesn't require user-interaction) or there just this one API and it is it simply our responsibility to observe these restrictions when we use it?

The `DISALLOW_INSTALL_UNKNOWN_SOURCES` and `DISALLOW_INSTALL_UNKNOWN_SOURCES_GLOBALLY` APIs definitely need to be checked manually since the way Seedvault is set up is how a known source of apps works. I'm less sure about `DISALLOW_INSTALL_APPS`, and it probably needs to be checked if that is currently being bypassed.

It's also possible to use these restrictions without a device manager if the OS exposes them via the Settings app for the configuration of user profiles. In the past, GrapheneOS used to expose various additional options there, including blocking app installs, but it hasn't restored this yet.

**Comment by jtagcat** [comment]
> Any app from the backup needs to be considered as coming from an unknown source

That might mess up app store ownership (not sure if it does atm as well).

If you've used gplay + fdroid on your device, you might've noticed, that magically gplay knows not to touch/update fdroid's apps, and fdroid does the same.

**Comment by thestinger** [comment]
That's not what I mean.

**Comment by eighthave** [comment]
How does a Google Play device with `DISALLOW_INSTALL_UNKNOWN_SOURCES` treat Google Play?  I imagine it lets apps be reinstalled from backup via Google Play.  In the use cases with Seedvauit built without Google Play, then something else serves as the "known source".  In the CalyxOS example, F-Droid is the built-in "known source", so in that case, it should not be restrict from installing apps when `DISALLOW_INSTALL_UNKNOWN_SOURCES` is enabled.

**Comment by chirayudesai** [comment]
> How does a Google Play device ...

One difference here is
* Google Play -> on backup restore, device asks Google Play to download the APK
* SeedVault -> APK can be included in the backup, and while it does store the `installerPackageName`, it does not store any more info (so it could be from any F-Droid repo for example). `installerPackageName` could also theoretically be modified.

The default probably needs to be follow the restrictions always, and while that would make backups not that useful, we can try to think of other ways around that if needed in an iteration since otherwise that becomes a bypass of the restriction.

**Comment by grote** [comment]
@chirayudesai I think this was completely addressed by https://github.com/seedvault-app/seedvault/pull/502 right?
