### ISSUE TITLE
Enabling and then disabling "backup my data" leads to unremovable error notification

### ISSUE THREAD

**Issue by axelsimon** [seedvault-app/seedvault#87]
Hi,
First of all, many thanks for making seedvault. We've needed a fully free Android backup solution that doesn't depend on for-profit, centralised services but "just works" for a *long time*.

Here's the issue i found: i enabled seedvault by activating "Backup my data", then went to pick a location. My Nextcloud server is currently unreachable, so i got an notification "Backup Error: a device backup failed to run". I stopped there and disabled seedvault backups.

But the seedvault notification now won't go away. Or to be more specific, it comes back a few seconds after being dismissed, no matter how many times it's dismissed.

Thanks!

**Comment by grote** [comment]
That's probably the OS trying to re-initialize the backup location after it had failed. However, it shouldn't do that if backup is completely disabled. Are you sure that this happens with backup turned off?

**Comment by axelsimon** [comment]
Unfortunately, yes, this happens with the backup disabled.

This is on GrapheneOS, where Seedvault is built-in (OS version QQ3A.200605.001.2020.06.02.02 if relevant).

**Comment by grote** [comment]
Do you know how to record a logcat of the relevant time-frame? Bonus points for only showing logs related to the issue. aka seedvault and `system_server`.

**Comment by axelsimon** [comment]
Sure, can do. Let me get that to you, although i need to check how much Graphene will let me get, first.

**Comment by axelsimon** [comment]
Sorry for the very slow reply, i wasn't able to get a log from an app on the phone and started looking into how to get a `logcat` from my laptop with just `com.stevesoltys.seedvault` *and* `system_server` but haven't found out how to get both, yet.

I haven't forgotten you however, so i'll get that to you soon! :)

**Comment by grote** [comment]
Thanks @axelsimon! On a computer you can run:

    adb logcat --pid=`adb shell pidof -s system_server`

and 

    adb logcat --pid=`adb shell pidof -s com.stevesoltys.seedvault`

**Comment by axelsimon** [comment]
Sorry, i think i caught some logs for you but then forgot about this issue. I'll check tomorrow.
